### ISSUE TITLE
[BUG] Second bouncer missing information

### ISSUE THREAD

**Issue by lordraiden** [maxlerebourg/crowdsec-bouncer-traefik-plugin#103]
**Describe the bug** 🐛
I have registered 2 Apps using the bouncer each with it's own middleware but only one of the look like proper registered

![imagen](https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/assets/17175395/14e25de9-f38e-4bdd-acfb-f2fd53725456)

**Expected behavior** 👀
IP and type columns fill out with info

**Context** 🔎

```
http:

# Home Assistant
  routers:

    homeassistant:
      entryPoints:
        - https443
      rule: 'Host(`ha.subzerocloud.com.es`)'
      service: homeassistant
      middlewares:
        - traefik-ha-csbouncer

    plex:
      entryPoints:
        - https443
      rule: 'Host(`plex.subzerocloud.com.es`)'
      service: plex
      middlewares:
        - traefik-plex-csbouncer
   
  services:

    homeassistant:
      loadBalancer:
        servers:
          - url: http://10.10.10.100:8123/

    plex:
      loadBalancer:
       servers:
          - url: http://10.10.50.20:32400/

  ## MIDDLEWARES ##
  middlewares:
    
    # Only Allow Local networks
    local-ipwhitelist:
      ipWhiteList:
        sourceRange: 
          - 10.10.10.1/24 # localhost

    traefik-ha-csbouncer:
      plugin:
        crowdsec-bouncer-traefik-plugin:
          enabled: true
          logLevel: INFO
          updateIntervalSeconds: 30 # stream mode only
          #defaultDecisionSeconds: 60 # live mode only
          crowdsecMode: stream
          crowdsecLapiKey: ssgsdgfsdfgdfgsdfgs# Api key for 'traefik-ha'
          crowdsecLapiHost: 10.10.50.11:8080
          crowdsecLapiScheme: http
          crowdsecLapiTLSInsecureVerify: false
          #forwardedHeadersTrustedIPs:   # List of IPs of trusted Proxies that are in front of traefik (ex: Cloudflare)
          clientTrustedIPs: 
            - 10.10.10.1/24
          forwardedHeadersCustomName: X-Forwarded-For
          #redisCacheEnabled: false
          #redisCacheHost: "redis:6379"
          #redisCachePassword: password
          #redisCacheDatabase: "5"

    traefik-plex-csbouncer:
      plugin:
        crowdsec-bouncer-traefik-plugin:
          enabled: true
          logLevel: INFO
          updateIntervalSeconds: 30 # stream mode only
          #defaultDecisionSeconds: 60 # live mode only
          crowdsecMode: stream
          crowdsecLapiKey: fgdgfdsfdgsdfgsdgfgfdssfgd# Api key for 'traefik-ha'
          crowdsecLapiHost: 10.10.50.11:8080
          crowdsecLapiScheme: http
          crowdsecLapiTLSInsecureVerify: false
          #forwardedHeadersTrustedIPs:   # List of IPs of trusted Proxies that are in front of traefik (ex: Cloudflare)
          clientTrustedIPs: 
            - 10.10.10.1/24
          forwardedHeadersCustomName: X-Forwarded-For
          #redisCacheEnabled: false
          #redisCacheHost: "redis:6379"
          #redisCachePassword: password
          #redisCacheDatabase: "5"
```

**Version (please complete the following information):**
Traefik 2.10
Docker compose
Plugins latest

Is this the right behavior? I have tested plex domain and If I add my local IP to the list it blocking me so it's working.
