### ISSUE TITLE
[HELP] invalid middleware type or middleware does not exist

### ISSUE THREAD

**Issue by Jikeh** [maxlerebourg/crowdsec-bouncer-traefik-plugin#138]
Hello, I've been trying to setup the crowdsec bouncer plugin but traefik is unable to load the middleware apparently. It's probably some misconfiguration problem but I went over it multiple times and I can't figure it out.

This is part of my static traefik.yaml

```
entryPoints:
  websecure:
    address: :443
    http:
      middlewares:
        - crowdsec@file

experimental:
  plugins:
    enabled: true
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.2.1-rc1
```

This is my middleware rule, in a dynamic configuration file:

```
http:
  middlewares:
    crowdsec:
      plugin:
        bouncer:
          enabled: true
          crowdsecMode: "live"
          crowdsecLapiHost: "crowdsec:8080"
          crowdsecLapiKey: /
```

From the logs it looks like the configuration is correctly loaded:
`level=debug msg="Configuration received: {"http":{"middlewares":{"crowdsec":{"plugin":{"bouncer":{"crowdsecLapiHost":"crowdsec:8080","crowdsecLapiKey":/,"crowdsecMode":"live","enabled":"true"}}}`

though traefik fails to apply the middleware to any host:
`
level=error msg="invalid middleware \"crowdsec@file\" configuration: invalid middleware type or middleware does not exist" entryPointName=websecure routerName=websecure-service@docker`

What am I missing? The only difference with the suggested configuration is that I put the middleware in the static configuration as a global one for my entry point, as I do with many other middlewares. Is that not supposed to be supported?
