### ISSUE TITLE
[BUG] Traefik v3 does not render correctly html ban page

### ISSUE THREAD

**Issue by aikooo7** [maxlerebourg/crowdsec-bouncer-traefik-plugin#162]
**Describe the bug** 🐛
When using the provided ban.html and providing it with the option, it gets printed even through the html renders if you test it in a html renderer.

**Expected behavior** 👀
The html getting rendered.

**Context** 🔎

Configuration:

```
- "traefik.http.middlewares.crowdsec.plugin.bouncer.enabled=true"
- "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdseclapikey=APIKEY"
- "traefik.http.middlewares.crowdsec.plugin.bouncer.logLevel=DEBUG"
- "traefik.http.middlewares.crowdsec.plugin.bouncer.banHTMLFilePath=/ban.html"
- "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecLapiHost=crowdsec:8080"
```

No error in logs were found.

**Version (please complete the following information):**
 - OS: Docker
 - Traefik version: 3.0.0
 - Plugin version: 1.3.0
 - Redis: ?

**To Reproduce**
1. Put configuration.
2. Activate middleware.
3. Ban yourself.
4. Try to go to the service.

**Comment by benscobie** [comment]
I suspect that this might be the change in v3 that causes this: https://doc.traefik.io/traefik/master/migration/v2-to-v3/#content-type-auto-detection

**Comment by mathieuHa** [comment]
Hi @aikooo7,

I've tried to reproduce with the minimal exemple [custom-ban-page](https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/tree/main/examples/custom-ban-page) updated recently to version 3 of Traefik.

`make run_custombanpage`
![image](https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/assets/16974644/51ca5d5e-89ca-4d06-a1dc-ad613a049e5e)

I then went to `http://localhost:8000/foo/` to get my IP from whoami and banned it in crowdsec container.  
after reloading /foo, I had the ban template correctly rendered.  

![image](https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/assets/16974644/4fca13a5-d2c9-4af7-a3b0-3e2ab20e8147)

The debug logs I have are the following:
```
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/05/06 16:12:22 getTLSConfigCrowdsec:CrowdsecLapiScheme https:no
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/05/06 16:12:22 cache:New initialized isRedis:false
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/05/06 16:12:22 New initialized mode:live
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/05/06 16:12:31 ServeHTTP ip:172.18.0.1 isTrusted:false
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/05/06 16:12:31 cache:Get key:172.18.0.1
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/05/06 16:12:31 ServeHTTP:Get ip:172.18.0.1 isBanned:false cache:miss
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/05/06 16:12:31 cache:Set key:172.18.0.1 value:f duration:60s
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/05/06 16:13:50 ServeHTTP ip:172.18.0.1 isTrusted:false
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/05/06 16:13:50 cache:Get key:172.18.0.1
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/05/06 16:13:50 ServeHTTP:Get ip:172.18.0.1 isBanned:false cache:miss
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/05/06 16:13:50 cache:Set key:172.18.0.1 value:t duration:60s
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/05/06 16:13:50 ServeHTTP:handleNoStreamCache ip:172.18.0.1 isBanned:t handleNoStreamCache:banned
DEBUG: CrowdsecBouncerTraefikPlugin: 2024/05/06 16:13:50 handleRemediationServeHTTP ip:172.18.0.1 remediation:t
```

Could you please try to test the minimal exemple custom-ban-page in the repository and see if it's working for you.  

If not, I would need more information (a docker-compose and every debug logs from the plugin) to try and reproduce.

**Comment by aikooo7** [comment]
Hey @mathieuHa, I appreciate your help a lot but the problem with the demo is that it conflicts with my configuration, even when I change the name on the docker compose it just turns out to be a mess.

Any other way I could fix this?

**Comment by aikooo7** [comment]
Hey @mathieuHa, I appreciate your help a lot but the problem with the demo is that it conflicts with my configuration, even when I change the name on the docker compose it just turns out to be a mess.

Any other way I could fix this?

Here is a screenshot of my problem in case it helps:

![Screenshot_20240506-234021_Firefox.png](https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/assets/79667753/60014c54-c3ac-436a-a0c6-02ed597385ca)

**Comment by aikooo7** [comment]
Hey @mathieuHa, I appreciate your help a lot but the problem with the demo is that it conflicts with my configuration, even when I change the name on the docker compose it just turns out to be a mess.

Any other way I could fix this?

Here is a screenshot of my problem in case it helps:

![Screenshot_20240506-234021_Firefox.png](https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/assets/79667753/60014c54-c3ac-436a-a0c6-02ed597385ca)

**Comment by xKhronoz** [comment]
Wanted to add on that I am experiencing this problem as well, though the demo works correctly and renders the ban.html page correctly, on my own installation, it does not and instead renders the  html as text, inspecting the page seems to shows that the html page got wrapped in between "\<pre\>\</pre\>" tags:

![image](https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/assets/21101460/0451d63e-82c8-4a9d-9b45-54aa8591ee5b)

Still investigating this problem though I am also using Cloudflare in front as well which could be another potential reason.

Using Traefik V3 and V1.3 Plugin.

**Comment by aikooo7** [comment]
> Still investigating this problem though I am also using Cloudflare in front as well which could have other potential stuff causing an issue, but i do have all the Auto-Minify and Rocket Loader off.

Apparently cloudflare is not the problem since I am not using it.

**Comment by maxlerebourg** [comment]
Hey all,

@benscobie: I don't think, it's related because in the code we have:
```go
func handleBanServeHTTP(bouncer *Bouncer, rw http.ResponseWriter) {
	rw.WriteHeader(http.StatusForbidden)
	if bouncer.banTemplateString != "" {
		rw.Header().Set("Content-Type", "text/html; charset=utf-8")
		fmt.Fprint(rw, bouncer.banTemplateString)
	}
}
```
We set the content type if the `BanHTMLFilePath` is set.


@xKhronoz: Could you share your docker-compose config, and debug logs from the launch of Traefik with our plugin.
Maybe try to put our plugin in the last middleware execution list.

**Comment by aikooo7** [comment]
> Hey all,
> 
> @benscobie: I don't think, it's related because in the code we have:
> ```go
> func handleBanServeHTTP(bouncer *Bouncer, rw http.ResponseWriter) {
> 	rw.WriteHeader(http.StatusForbidden)
> 	if bouncer.banTemplateString != "" {
> 		rw.Header().Set("Content-Type", "text/html; charset=utf-8")
> 		fmt.Fprint(rw, bouncer.banTemplateString)
> 	}
> }
> ```

If I understand correctly and you mean it is related to cloudflare then why would I get it?

**Comment by xKhronoz** [comment]
I might have found the root cause of the issue, at least with regards to the way I setup Traefik, Crowdsec, and my other service, as I separate my services into their own docker-compose files, with the use of the 'Dynamic' Configuration File to setup a few common Middlewares that are shared across my services and the use of 'Chain' Middleware to combine these middleware into one, including this plugin, and as mentioned by @benscobie indeed that with Traefik V3, automatic content type auto detection has to be set to true in the config in order for it to be working, although I am not 100% sure if the problem happens due to there being more than 1 middleware in used for a service and somehow content type auto detection is not working or smth, but adding in the auto content type detection finally got the html page to be rendered correctly.

https://doc.traefik.io/traefik/middlewares/http/contenttype/



> Hey all,
> 
> @benscobie: I don't think, it's related because in the code we have:
> 
> ```go
> func handleBanServeHTTP(bouncer *Bouncer, rw http.ResponseWriter) {
> 	rw.WriteHeader(http.StatusForbidden)
> 	if bouncer.banTemplateString != "" {
> 		rw.Header().Set("Content-Type", "text/html; charset=utf-8")
> 		fmt.Fprint(rw, bouncer.banTemplateString)
> 	}
> }
> ```
> 
> We set the content type if the `BanHTMLFilePath` is set.
> 
> @xKhronoz: Could you share your docker-compose config, and debug logs from the launch of Traefik with our plugin. Maybe try to put our plugin in the last middleware execution list.

@mathieuHa yes before i added the auto content type detection, I had tried to move the plugin to the last in my middleware chain but it did not work as well, however adding the auto content type detection middleware to before the plugin middleware as well did the trick.

**Middleware Chain Screenshot**
![image](https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/assets/21101460/33916489-3324-47ec-9233-2e4005bffc4b)

**My sanitized dynamic config.yaml for Traefik**
```
# Dynamic Config File

# TLS Config
tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        # TLS 1.3
        - "TLS_AES_256_GCM_SHA384"
        - "TLS_AES_128_GCM_SHA256"
        - "TLS_CHACHA20_POLY1305_SHA256"

        # TLS 1.2
        - "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256"
        - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
        - "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
        - "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
        - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"

        # Downgrade attack prevention (RFC 7507)
        - "TLS_FALLBACK_SCSV"
      curvePreferences:
        - CurveP521
        - CurveP384
      clientAuth:
        caFiles:
          # mTLS with CF Origin CA
          - /authenticated_origin_pull_ca.pem
        clientAuthType: RequireAndVerifyClientCert
    mintls13:
      minVersion: VersionTLS13
      sniStrict: true

# HTTP Config
http:
  middlewares:
    security-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        hostsProxyHeaders: X-Forwarded-Host
        sslProxyHeaders:
          X-Forwarded-Proto: https
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 63072000 # 2 Years https://hstspreload.org/
        referrerPolicy: same-origin
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
        customResponseHeaders:
          X-Robots-Tag: "noindex, nofollow, nosnippet, noarchive, notranslate, noimageindex"

    autodetect-contenttype:
      contentType: {}

    rate-limiter:
      rateLimit:
        average: 100
        burst: 50

    crowdsec-bouncer:
      plugin:
        crowdsec-bouncer-traefik-plugin:
          Enabled: true
          LogLevel: INFO
          CrowdsecLapiHost: crowdsec:8080
          CrowdsecLapiKey: REDACTED
          CrowdsecMode: stream
          UpdateIntervalSeconds: 10
          UpdateMaxFailure: 5
          ForwardedHeadersTrustedIPs:
            # CF IP Range
            - 103.21.244.0/22
            - 103.22.200.0/22
            - 103.31.4.0/22
            - 104.16.0.0/13
            - 104.24.0.0/14
            - 108.162.192.0/18
            - 131.0.72.0/22
            - 141.101.64.0/18
            - 162.158.0.0/15
            - 172.64.0.0/13
            - 173.245.48.0/20
            - 188.114.96.0/20
            - 190.93.240.0/20
            - 197.234.240.0/22
            - 198.41.128.0/17
            - 2400:cb00::/32
            - 2606:4700::/32
            - 2803:f800::/32
            - 2405:b500::/32
            - 2405:8100::/32
            - 2a06:98c0::/29
            - 2c0f:f248::/32
          ClientTrustedIPs:
            - 127.0.0.1/24 # LocalHost
            - 10.0.0.0/8 # Private IP Range
            - 192.168.0.0/16 # Private IP Range
            - 172.16.0.0/12 # Private IP Range
            - 100.64.0.0/10 # Tailscale IP Range
          BanHTMLFilePath: /ban.html
          RedisCacheEnabled: true
          RedisCacheHost: crowdsec-traefik-bouncer-redis:6379
          RedisCachePassword: REDACTED
          RedisCacheDatabase: "5"

    # For External Access Services
    external-secured:
      chain:
        middlewares:
          - rate-limiter
          - autodetect-contenttype
          - security-headers
          - crowdsec-bouncer
```
