### ISSUE TITLE
[BUG] Block Acces

### ISSUE THREAD

**Issue by skyguy2002** [maxlerebourg/crowdsec-bouncer-traefik-plugin#181]
**Describe the bug** 🐛
As soon as I activate the middleware, I no longer have access to the page, although nothing is displayed according to the “cscli decisions list”

**Expected behavior** 👀
Actually, since my IP is not blocked, I should have access

**Context** 🔎
Middleware file:
```yaml
http:
  middlewares:
    crowdsec:
      plugin:
        bouncer:
          enabled: true
          logLevel: INFO
          crowdsecMode: none
          crowdsecLapiScheme: http
          crowdsecLapiHost: localhost:8000
          crowdsecLapiKey: 01747c4972397ebc94ac0ce94281583f
```
Service file:
```yaml
http:
  routers:
    traefik:
      entryPoints:
      - websecure
      middlewares:
      - basicauth
      - crowdsec
      tls: {}
      service: api@internal
      rule: “Host(`traefik.XXX.de`)”
```

**Version (please complete the following information):**
 - OS: Ubuntu 24.02
 - Traefik version: v3.1.0
 - Plugin version: v1.3.2

**To Reproduce**
1. add middleware
2. configure as described above
3. add LapiKey and URL
4. try to get to the page
