### ISSUE TITLE
When enabling the plugin, all traffic is stopped

### ISSUE THREAD

**Issue by GD-Dal** [maxlerebourg/crowdsec-bouncer-traefik-plugin#199]
I'm struggling to make this plugin work.
As soon as I go _**enabled: true**_ in the Traefik Dynamic file, all traffic to docker containers behind Traefik gets an 403 error. Both from local addresses and external adresses

This is the config from traefik.yml:

```
entryPoints:
  http:
    address: :80
    # forwardedHeaders:
    forwardedHeaders:
      insecure: true
    http:
      middlewares:
        - crowdsec@file
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: :443
    forwardedHeaders:
      insecure: true
    http:
      middlewares:
        - crowdsec@file
        - securityHeaders@file
      tls:
        # Generate a wildcard domain certificate
        certResolver: letsencrypt
        domains:
          - main: domain.net
            sans:
              - '*.domain.net'
providers:
  providersThrottleDuration: 2s

  file:
    directory: /etc/traefik/dynamic
    watch: true

  docker:
    watch: true
    network: frontend # Add Your Docker Network Name Here
    exposedByDefault: false

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG
  filePath: /etc/traefik/log/logfile.log
  #format: json
accessLog:
  filePath: /etc/traefik/log/access.log

experimental:
  plugins:
    crowdsec-bouncer-traefik-plugin:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.3.5"
```

This is from the dynamic Traefik file:
```

http:
  middlewares:
    crowdsec:
      plugin:
        crowdsec-bouncer-traefik-plugin:
          enabled: false
          crowdsecAppsecEnabled: true
          crowdsecAppsecHost: crowdsec:7422
          crowdsecAppsecFailureBlock: true
          crowdsecAppsecUnreachableBlock: true
          updateIntervalSeconds: 15
          updateMaxFailure: 0
          defaultDecisionSeconds: 15
          httpTimeoutSeconds: 10
          crowdsecMode: stream
          crowdsecLapiHost: crowdsec:8080
          crowdsecLapiKey: nope
          forwardedHeadersTrustedIPs: 
            - 127.0.0.1
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 172.20.0.0/16
            - 192.168.0.0/16
            - 2a03:67ab:ea01:eaaa::/56
          clientTrustedIPs:
            - 127.0.0.1
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 172.20.0.0/16
            - 192.168.0.0/16
            - 2a03:67ab:ea01:eaaa::/56
          logLevel: INFO
    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          X-Forwarded-Proto: "https"
          server: ""
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "same-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
    gzip:
      compress: {}
```

I don't understand what could be wrong here.

The CSCLI metrics looks happy to me as well:

```
/ # cscli metrics
Acquisition Metrics:
╭────────────────────────────────────────┬────────────┬──────────────┬────────────────┬────────────────────────┬───────────────────╮
│ Source                                 │ Lines read │ Lines parsed │ Lines unparsed │ Lines poured to bucket │ Lines whitelisted │
├────────────────────────────────────────┼────────────┼──────────────┼────────────────┼────────────────────────┼───────────────────┤
│ file:/var/log/traefik_logs/access.log  │ 27.84k     │ 27.84k       │ -              │ 3.97k                  │ 21.10k            │
│ file:/var/log/traefik_logs/logfile.log │ 32.02k     │ -            │ 32.02k         │ -                      │ -                 │
╰────────────────────────────────────────┴────────────┴──────────────┴────────────────┴────────────────────────┴───────────────────╯

Local API Alerts:
╭────────────────────────────────────────────┬───────╮
│ Reason                                     │ Count │
├────────────────────────────────────────────┼───────┤
│ crowdsecurity/CVE-2022-35914               │ 1     │
│ crowdsecurity/http-path-traversal-probing  │ 7     │
│ crowdsecurity/http-sensitive-files         │ 3     │
│ crowdsecurity/CVE-2017-9841                │ 1     │
│ crowdsecurity/http-probing                 │ 14    │
│ crowdsecurity/http-crawl-non_statics       │ 5     │
│ crowdsecurity/http-cve-2021-41773          │ 2     │
│ crowdsecurity/http-xss-probbing            │ 1     │
│ crowdsecurity/netgear_rce                  │ 1     │
│ crowdsecurity/http-admin-interface-probing │ 15    │
│ crowdsecurity/CVE-2022-41082               │ 3     │
│ crowdsecurity/fortinet-cve-2018-13379      │ 1     │
│ crowdsecurity/http-backdoors-attempts      │ 1     │
│ crowdsecurity/http-cve-probing             │ 1     │
│ crowdsecurity/jira_cve-2021-26086          │ 1     │
│ crowdsecurity/thinkphp-cve-2018-20062      │ 1     │
│ crowdsecurity/CVE-2022-26134               │ 1     │
╰────────────────────────────────────────────┴───────╯

Local API Decisions:
╭────────────────────────────────────────────┬────────┬────────┬───────╮
│ Reason                                     │ Origin │ Action │ Count │
├────────────────────────────────────────────┼────────┼────────┼───────┤
│ crowdsecurity/CVE-2023-22515               │ CAPI   │ ban    │ 14    │
│ crowdsecurity/CVE-2023-49103               │ CAPI   │ ban    │ 82    │
│ crowdsecurity/ssh-cve-2024-6387            │ CAPI   │ ban    │ 45    │
│ ltsich/http-w00tw00t                       │ CAPI   │ ban    │ 5     │
│ crowdsecurity/CVE-2022-44877               │ CAPI   │ ban    │ 1     │
│ crowdsecurity/http-crawl-non_statics       │ CAPI   │ ban    │ 601   │
│ crowdsecurity/ssh-slow-bf                  │ CAPI   │ ban    │ 9060  │
│ crowdsecurity/thinkphp-cve-2018-20062      │ CAPI   │ ban    │ 267   │
│ crowdsecurity/CVE-2022-26134               │ CAPI   │ ban    │ 13    │
│ crowdsecurity/f5-big-ip-cve-2020-5902      │ CAPI   │ ban    │ 4     │
│ crowdsecurity/http-admin-interface-probing │ CAPI   │ ban    │ 297   │
│ crowdsecurity/http-sensitive-files         │ CAPI   │ ban    │ 541   │
│ crowdsecurity/CVE-2022-35914               │ CAPI   │ ban    │ 11    │
│ crowdsecurity/apache_log4j2_cve-2021-44228 │ CAPI   │ ban    │ 55    │
│ crowdsecurity/http-cve-2021-42013          │ CAPI   │ ban    │ 7     │
│ crowdsecurity/http-open-proxy              │ CAPI   │ ban    │ 2931  │
│ crowdsecurity/CVE-2017-9841                │ CAPI   │ ban    │ 497   │
│ crowdsecurity/fortinet-cve-2018-13379      │ CAPI   │ ban    │ 21    │
│ crowdsecurity/http-bad-user-agent          │ CAPI   │ ban    │ 12724 │
│ crowdsecurity/http-cve-probing             │ CAPI   │ ban    │ 41    │
│ crowdsecurity/CVE-2022-37042               │ CAPI   │ ban    │ 2     │
│ crowdsecurity/http-cve-2021-41773          │ CAPI   │ ban    │ 632   │
│ crowdsecurity/jira_cve-2021-26086          │ CAPI   │ ban    │ 19    │
│ crowdsecurity/CVE-2024-0012                │ CAPI   │ ban    │ 1     │
│ crowdsecurity/http-generic-bf              │ CAPI   │ ban    │ 38    │
│ crowdsecurity/http-probing                 │ CAPI   │ ban    │ 7302  │
│ crowdsecurity/http-wordpress-scan          │ CAPI   │ ban    │ 1170  │
│ crowdsecurity/netgear_rce                  │ CAPI   │ ban    │ 144   │
│ crowdsecurity/spring4shell_cve-2022-22965  │ CAPI   │ ban    │ 1     │
│ crowdsecurity/ssh-bf                       │ CAPI   │ ban    │ 7780  │
│ crowdsecurity/CVE-2019-18935               │ CAPI   │ ban    │ 81    │
│ crowdsecurity/grafana-cve-2021-43798       │ CAPI   │ ban    │ 4     │
│ crowdsecurity/http-backdoors-attempts      │ CAPI   │ ban    │ 192   │
│ crowdsecurity/http-path-traversal-probing  │ CAPI   │ ban    │ 325   │
╰────────────────────────────────────────────┴────────┴────────┴───────╯

Local API Metrics:
╭──────────────────────┬────────┬───────╮
│ Route                │ Method │ Hits  │
├──────────────────────┼────────┼───────┤
│ /v1/alerts           │ GET    │ 2     │
│ /v1/alerts           │ POST   │ 2     │
│ /v1/decisions/stream │ GET    │ 10484 │
│ /v1/heartbeat        │ GET    │ 2620  │
│ /v1/usage-metrics    │ POST   │ 88    │
│ /v1/watchers/login   │ POST   │ 47    │
╰──────────────────────┴────────┴───────╯

Local API Bouncers Metrics:
╭───────────────────────────────────┬──────────────────────┬────────┬───────╮
│ Bouncer                           │ Route                │ Method │ Hits  │
├───────────────────────────────────┼──────────────────────┼────────┼───────┤
│ traefik-bouncer-plugin@172.20.0.6 │ /v1/decisions/stream │ GET    │ 10484 │
╰───────────────────────────────────┴──────────────────────┴────────┴───────╯

Local API Machines Metrics:
╭───────────┬───────────────┬────────┬──────╮
│ Machine   │ Route         │ Method │ Hits │
├───────────┼───────────────┼────────┼──────┤
│ localhost │ /v1/alerts    │ GET    │ 2    │
│ localhost │ /v1/alerts    │ POST   │ 2    │
│ localhost │ /v1/heartbeat │ GET    │ 2620 │
╰───────────┴───────────────┴────────┴──────╯

Parser Metrics:
╭──────────────────────────────────┬────────┬────────┬──────────╮
│ Parsers                          │ Hits   │ Parsed │ Unparsed │
├──────────────────────────────────┼────────┼────────┼──────────┤
│ child-crowdsecurity/http-logs    │ 83.52k │ 67.33k │ 16.20k   │
│ child-crowdsecurity/traefik-logs │ 59.86k │ 27.84k │ 32.02k   │
│ crowdsecurity/dateparse-enrich   │ 27.84k │ 27.84k │ -        │
│ crowdsecurity/geoip-enrich       │ 2.09k  │ 2.09k  │ -        │
│ crowdsecurity/http-logs          │ 27.84k │ 27.84k │ -        │
│ crowdsecurity/non-syslog         │ 59.86k │ 59.86k │ -        │
│ crowdsecurity/traefik-logs       │ 59.86k │ 27.84k │ 32.02k   │
│ crowdsecurity/whitelists         │ 27.84k │ 27.84k │ -        │
╰──────────────────────────────────┴────────┴────────┴──────────╯

Scenario Metrics:
╭────────────────────────────────────────────┬───────────────┬───────────┬──────────────┬────────┬─────────╮
│ Scenario                                   │ Current Count │ Overflows │ Instantiated │ Poured │ Expired │
├────────────────────────────────────────────┼───────────────┼───────────┼──────────────┼────────┼─────────┤
│ crowdsecurity/CVE-2017-9841                │ -             │ 1         │ 1            │ -      │ -       │
│ crowdsecurity/CVE-2022-41082               │ -             │ 1         │ 1            │ -      │ -       │
│ crowdsecurity/http-admin-interface-probing │ -             │ -         │ 5            │ 7      │ 5       │
│ crowdsecurity/http-backdoors-attempts      │ -             │ -         │ 1            │ 1      │ 1       │
│ crowdsecurity/http-crawl-non_statics       │ -             │ -         │ 1.96k        │ 3.33k  │ 1.96k   │
│ crowdsecurity/http-probing                 │ -             │ -         │ 549          │ 626    │ 549     │
│ crowdsecurity/http-sensitive-files         │ -             │ -         │ 12           │ 12     │ 12      │
╰────────────────────────────────────────────┴───────────────┴───────────┴──────────────┴────────┴─────────╯

Whitelist Metrics:
╭──────────────────────────┬─────────────────────────────┬───────┬─────────────╮
│ Whitelist                │ Reason                      │ Hits  │ Whitelisted │
├──────────────────────────┼─────────────────────────────┼───────┼─────────────┤
│ crowdsecurity/whitelists │ private ipv4/ipv6 ip/ranges │ 27841 │ 21102       │
╰──────────────────────────┴─────────────────────────────┴───────┴─────────────╯

/ # 
/ # 
```
What am I missing?

Thanks

**Comment by mathieuHa** [comment]
Hi @GD-Dal,

If Traefik block 100% of requests it probably means it cant reach the LAPI or the Appsec component since you enabled:
```
          crowdsecAppsecFailureBlock: true
          crowdsecAppsecUnreachableBlock: true
          updateMaxFailure: 0
```

Could you enable the plugin debug logs and provide them from Traefik Start to some requests you make. 
In 90% of cases, this is enough to identify what is causing the communication issue.

Thanks in advance

**Comment by GD-Dal** [comment]
Thank you.
I changed the crowdsecAppsecEnabled from true to false, and it started working.
The question remains, though; why doesn't appsec work?
Maybe because of the port 7422 is exposed in the docker container? Will test

Thanks again

**Comment by maxlerebourg** [comment]
Hey @GD-Dal, you forgot to add the crowdsec collections that handle appsec.

This crowdsec config is from our "appsec-enabled" example, see the env var `COLLECTIONS`:
```yaml
crowdsec:
    image: crowdsecurity/crowdsec:v1.6.1-2
    container_name: "crowdsec"
    restart: unless-stopped
    environment:
      COLLECTIONS: crowdsecurity/traefik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules
      CUSTOM_HOSTNAME: crowdsec
      BOUNCER_KEY_TRAEFIK_DEV: 40796d93c2958f9e58345514e67740e5
    volumes:
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      - logs-appsec-enabled:/var/log/traefik:ro
      - crowdsec-db-appsec-enabled:/var/lib/crowdsec/data/
      - crowdsec-config-appsec-enabled:/etc/crowdsec/
    labels:
      - "traefik.enable=false"
```
