### ISSUE TITLE
[BUG] My short bug title

### ISSUE THREAD

**Issue by fregapple** [maxlerebourg/crowdsec-bouncer-traefik-plugin#219]
**Describe the bug** 🐛
Looking within the CrowdSec Console, traefik-bouncer is unknown version and there is no metrics.
Going into crowdsec container and checking the metrics of the bouncer I get this:
```
cscli bouncers inspect traefik-bouncer

───────────────────────────────────────────────────────
 Bouncer: traefik-bouncer                              
───────────────────────────────────────────────────────
 Created At    2025-02-18 03:00:04.951715543 +0000 UTC 
 Last Update   2025-02-18 03:00:04.951715699 +0000 UTC 
 Revoked?      false                                   
 IP Address                                            
 Type                                                  
 Version                                               
 Last Pull                                             
 Auth type     api-key                                 
 OS            ?                                       
 Auto Created  false  

```
I am able to use traefik as normal

**Expected behavior** 👀
I would hope that I would be able to see metrics and know if this bouncer is doing anything?

**Context** 🔎
plugin config:
```
    middlewares-crowdsec:
      plugin:
        bouncer:
          enabled: true
          logLevel: debug
          crowdsecLapiKey: <KEY>
          crowdsecLapiHost: crowdsec:8888
          crowdsecAppsecEnabled: true
          crowdsecAppsecHost: crowdsec:7422
          forwardedHeadersTrustedIPs:
            - 173.245.48.0/20
            - 103.21.244.0/22
            - 103.22.200.0/22
            - 103.31.4.0/22
            - 141.101.64.0/18
            - 108.162.192.0/18
            - 190.93.240.0/20
            - 188.114.96.0/20
            - 197.234.240.0/22
            - 198.41.128.0/17
            - 162.158.0.0/15
            - 104.16.0.0/13
            - 104.24.0.0/14
            - 172.64.0.0/13
            - 131.0.72.0/22
          clientTrustedIPs:
            - 192.168.1.0/24

```
**Version (please complete the following information):**
 - OS: Ubunto
 - Traefik version: 3.0.4
 - Plugin version: 1.4.2

**Comment by fregapple** [comment]
Actually, scratch that about traefik working normally. While testing I had commented out the crowdsec middleware from the chain file. readding it causes a 404.

**Comment by fregapple** [comment]
In my Log i am getting: 

```
2025-02-18T16:36:20+11:00 ERR github.com/traefik/traefik/v3/pkg/server/router/router.go:136 > error="invalid middleware \"crowdsec@file\" configuration: invalid middleware type or middleware does not exist" 
```

**Comment by fregapple** [comment]
ANNND Further into the log:

```
2025-02-18T16:42:20+11:00 ERR github.com/traefik/traefik/v3/cmd/traefik/traefik.go:230 > Plugins are disabled because an error has occurred. error="unable to set up plugins environment: unable to download plugin github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin: failed to call service: Get \"https://plugins.traefik.io/public/download/github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/v1.4.2\": GET https://plugins.traefik.io/public/download/github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/v1.4.2 giving up after 4 attempt(s)"
```

**Comment by fregapple** [comment]
Alright, I seemed to have solved this myself. I needed to name

```
middlewares:
  crowdsec:
    plugin:
      bouncers: <---- to ----> crowdsec-bouncer-traefik-plugin:
```
