### ISSUE TITLE
[QUESTION] crowdsecLapiKeyFile not working but crowdsecLapiKey is

### ISSUE THREAD

**Issue by strombringer** [maxlerebourg/crowdsec-bouncer-traefik-plugin#221]
Hi everyone. I'm trying to configure the bouncer with a Docker secret, but it's not working.

If I configure everything via `crowdsecLapiKey`, either by hardcoding the API key in the middleware config or loading it via a hardcoded environment value from the docker-compose file, everything works.

But when I use `crowdsecLapiKeyFile` with the Docker secret path, I keep getting 403 responses.

## Configuration

Traefik middleware config
```yaml
http:
  middlewares:    
    crowdsec:
      plugin:
        bouncer:
            crowdsecLapiKey: p47c+jFjj6qsLQ0AJ34thcoDJOsvCWJ2z5NVzGBWjj4 # works
            crowdsecLapiKey: {{ env "CROWDSEC_TEST_API_KEY" }} # works
            crowdsecLapiKeyFile: {{ env "CROWDSEC_BOUNCER_API_KEY" }} # does not work
            crowdsecLapiHost: crowdsec:8080
            enabled: true
            logLevel: DEBUG
            banHtmlFilePath: /etc/traefik/html/ban.html
```

docker-compose.yml
```
services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: "1001:1001"
    ports:
      - "80:80"
      - "81:81" # external http
      - "443:443"
      - "444:444" # external https
    secrets:
      - CROWDSEC_API_KEY_SECRET
    environment:
      CROWDSEC_BOUNCER_API_KEY: /run/secrets/CROWDSEC_API_KEY_SECRET
      CROWDSEC_TEST_API_KEY: p47c+jFjj6qsLQ0AJ34thcoDJOsvCWJ2z5NVzGBWjj4
    volumes:
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/conf:/etc/traefik/conf:ro
      - ./config/.htpasswd:/etc/traefik/.htpasswd:ro
      - ./config/acme.json:/etc/traefik/acme.json
      - ./html/ban.html:/etc/traefik/html/ban.html:ro
      - ./plugins-storage:/plugins-storage
      - ./logs:/var/log/traefik
    networks:
      - proxy

secrets:
  CROWDSEC_API_KEY_SECRET:
    file: './secrets/CROWDSEC_API_KEY_SECRET'

networks:
  proxy:
    external: true
```

## Logs

traefik.log with ENV KEY and hardcoded
-> correct key is shown
```
DBG github.com/traefik/traefik/v3/pkg/server/configurationwatcher.go:227 > Configuration received config={"http":{"middlewares":{"crowdsec":{"plugin":{"bouncer":{"banHtmlFilePath":"/etc/traefik/html/ban.html","crowdsecLapiHost":"crowdsec:8080","crowdsecLapiKey":"p47c+jFjj6qsLQ0AJ34thcoDJOsvCWJ2z5NVzGBWjj4","enabled":"true","logLevel":"DEBUG"}}},
```

traefik.log with ENV KEY FILE
-> correct path is shown
```
DBG github.com/traefik/traefik/v3/pkg/server/configurationwatcher.go:227 > Configuration received config={"http":{"middlewares":{"crowdsec":{"plugin":{"bouncer":{"banHtmlFilePath":"/etc/traefik/html/ban.html","crowdsecLapiHost":"crowdsec:8080","crowdsecLapiKeyFile":"/run/secrets/CROWDSEC_API_KEY_SECRET","enabled":"true","logLevel":"DEBUG"}}},
```

bouncer log when forbidden:
```
DEBUG: CrowdsecBouncerTraefikPlugin: 2025/03/08 10:37:53 cache:Set key:192.168.178.119 value:t duration:60s
DEBUG: CrowdsecBouncerTraefikPlugin: 2025/03/08 10:37:53 ServeHTTP:handleNoStreamCache ip:192.168.178.119 isBanned:t handleNoStreamCache:banned
DEBUG: CrowdsecBouncerTraefikPlugin: 2025/03/08 10:37:53 handleRemediationServeHTTP ip:192.168.178.119 remediation:t
DEBUG: CrowdsecBouncerTraefikPlugin: 2025/03/08 10:37:53 ServeHTTP ip:192.168.178.119 isTrusted:false
DEBUG: CrowdsecBouncerTraefikPlugin: 2025/03/08 10:37:53 cache:Get key:192.168.178.119
DEBUG: CrowdsecBouncerTraefikPlugin: 2025/03/08 10:37:53 ServeHTTP ip:192.168.178.119 cache:hit isBanned:t
DEBUG: CrowdsecBouncerTraefikPlugin: 2025/03/08 10:37:53 handleRemediationServeHTTP ip:192.168.178.119 remediation:t
```

## Checking secret from inside traefik container

Connecting to traefik container
```
docker exec -it traefik sh
```

Inside traefik container
```
/run/secrets $ ls -al
total 12
drwxr-xr-x    2 root     root          4096 Mar  8 10:30 .
drwxr-xr-x    1 root     root          4096 Mar  8 10:30 ..
-rw-------    1 1001     1001            44 Mar  7 15:30 CROWDSEC_API_KEY_SECRET
```

So the mounted secret is readable by the traefik user and the content of the file is the expected API key.

I don't see any errors in the logs, either by traefik itself or the bouncer plugin, except for the "isBanned:t" entries.

Do you have any idea what the issue might be? Am I even using Docker secrets correctly?
