### ISSUE TITLE
[BUG] crowdsecAppsecUnreachableBlock is keep throwing 403 forbidden if crowdsec container is down

### ISSUE THREAD

**Issue by maltsev-gorskij** [maxlerebourg/crowdsec-bouncer-traefik-plugin#224]
**Describe the bug** 🐛
I have a traefik and crowdsec running as two separate docker swarm stacks. 
They are communicating through overlay docker network "traefik_default"

I'm using both params to guarantee web services to work if any issue with crowdsec may appear.
crowdsecAppsecFailureBlock=false
crowdsecAppsecUnreachableBlock=false

If i stop crowdsec stack, traefik keep throwing 403 http codes on me.

```
$ curl -I https://mydomain.ru/
HTTP/2 403
date: Sun, 23 Mar 2025 20:53:02 GMT
```

Traefik debug log when i try connecting to some crowdsec protected host when crowdsec is down:
```
DEBUG: CrowdsecBouncerTraefikPlugin: 2025/03/23 23:31:31 ServeHTTP ip:51.159.250.232 isTrusted:false
DEBUG: CrowdsecBouncerTraefikPlugin: 2025/03/23 23:31:31 cache:Get key:51.159.250.232
DEBUG: CrowdsecBouncerTraefikPlugin: 2025/03/23 23:31:31 ServeHTTP:Get ip:51.159.250.232 isBanned:false cache:miss
DEBUG: CrowdsecBouncerTraefikPlugin: 2025/03/23 23:31:31 ServeHTTP:handleNoStreamCache ip:51.159.250.232 isBanned:t crowdsecQuery:unreachable url:http://crowdsec_crowdsec:8080/v1/decisions?ip=51.159.250.232&banned=true Get "http://crowdsec_crowdsec:8080/v1/decisions?ip=51.159.250.232&banned=true": dial tcp: lookup crowdsec_crowdsec on 127.0.0.11:53: no such host
DEBUG: CrowdsecBouncerTraefikPlugin: 2025/03/23 23:31:31 handleRemediationServeHTTP ip:51.159.250.232 remediation:t
```

I'v tried none, live, steam crowdsecMode values and they all have the same behavior of throwing 403 code on me when crowdsec is down.

Please help to debug this issue. 

**Expected behavior** 👀
Traefik keep working same as if crowdsec stack was up.

**Context** 🔎
Traefik docker swarm stack
```
services:
  traefik:
    image: dockerhub.timeweb.cloud/traefik:v3.3.4@sha256:cc11989f418e2cfe5e60fc40c92c1813be847f58eda15eced7d5ac890255ad9e
    command:
      - --log.level=DEBUG
      - --accesslog=true
      - --accesslog.filepath=/logs/access.log
      - --accesslog.format=json
      - --accesslog.filters.statuscodes=200-299,400-599
      - --accesslog.bufferingsize=0
      - --accesslog.fields.headers.defaultmode=drop
      - --accesslog.fields.headers.names.User-Agent=keep
      - --accesslog.fields.names.StartUTC=drop
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
      - --providers.swarm.endpoint=unix:///var/run/docker.sock
      - --providers.swarm.exposedbydefault=false
      - --providers.swarm.watch=true
      - --providers.swarm.network=traefik_default
      - --api.dashboard=true
      - --api.insecure=false
      - --entrypoints.web.address=:80
      - --entryPoints.web.forwardedHeaders.trustedIPs=0.0.0.0/0
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entryPoints.websecure.forwardedHeaders.trustedIPs=0.0.0.0/0
      - --entryPoints.2456-udp.address=:2456/udp
      - --entryPoints.2457-udp.address=:2457/udp
      - --entryPoints.2458-udp.address=:2458/udp
      - --entryPoints.3456-udp.address=:3456/udp
      - --certificatesresolvers.staging.acme.email=placeholder
      - --certificatesresolvers.staging.acme.storage=/ssl-certs/staging_acme.json
      - --certificatesresolvers.staging.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.staging.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.production.acme.email=placeholder
      - --certificatesresolvers.production.acme.storage=/ssl-certs/production_acme.json
      - --certificatesresolvers.production.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.production.acme.httpchallenge.entrypoint=web
      - --experimental.plugins.bouncer.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      - --experimental.plugins.bouncer.version=v1.4.1
    environment:
      - TZ=placeholder
    volumes:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
        read_only: true
      - source: traefik_ssl_certs
        target: /ssl-certs
        type: volume
      - source: traefik_logs
        target: /logs
        type: volume
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 2456
        published: 2456
        protocol: udp
        mode: host
      - target: 2457
        published: 2457
        protocol: udp
        mode: host
      - target: 2458
        published: 2458
        protocol: udp
        mode: host
      - target: 3456
        published: 3456
        protocol: udp
        mode: host
    networks:
      - traefik_default
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        delay: 15s
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        max_attempts: 5
        delay: 30s
        window: 600s
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik-dashbord.rule=Host(`placeholder`)"
        - "traefik.http.routers.traefik-dashbord.tls=true"
        - "traefik.http.routers.traefik-dashbord.tls.certresolver=production"
        - "traefik.http.routers.traefik-dashbord.entrypoints=websecure"
        - "traefik.http.routers.traefik-dashbord.service=api@internal"
        - "traefik.http.routers.traefik-dashbord.middlewares=traefik-dashbord-auth@swarm, crowdsec@swarm"
        - "traefik.http.services.dummy-svc.loadbalancer.server.port=9999"
        - "traefik.http.middlewares.traefik-dashbord-auth.basicauth.users=placeholder"

        - "traefik.http.middlewares.crowdsec.plugin.bouncer.enabled=true"
        - "traefik.http.middlewares.crowdsec.plugin.bouncer.LogLevel=DEBUG"
        - "traefik.http.middlewares.crowdsec.plugin.bouncer.defaultDecisionSeconds=60"
        - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecMode=live"
        - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecAppsecEnabled=true"
        - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecAppsecHost=crowdsec_crowdsec:7422"
        - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecAppsecFailureBlock=false"
        - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecAppsecUnreachableBlock=false"
        - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecLapiKey=placeholder"
        - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecLapiHost=crowdsec_crowdsec:8080"
        - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecLapiScheme=http"
        - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdsecLapiTLSInsecureVerify=false"
volumes:
  traefik_ssl_certs:
    name: traefik_ssl_certs
    driver: local
  traefik_logs:
    name: traefik_logs
    external: true

networks:
  traefik_default:
    name: traefik_default
    external: true
```

Crowdsec swarm stack
```
# Swarm stack name: crowdsec

services:
  crowdsec:
    image: dockerhub.timeweb.cloud/crowdsecurity/crowdsec:v1.6.6@sha256:d5049e83daf5399a83bf521389c7c5a0aa345e3ffcbfc0341ea51347a202f188
    volumes:
      - source: traefik_logs
        target: /logs/traefik
        type: volume
        read_only: true
      - source: crowdsec_configs
        target: /etc/crowdsec
        type: volume
      - source: crowdsec_data
        target: /var/lib/crowdsec/data
        type: volume
    environment:
      - TZ=placeholder
      - GID=1000
      - COLLECTIONS=crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/base-http-scenarios crowdsecurity/sshd crowdsecurity/linux crowdsecurity/appsec-generic-rules crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-crs
    networks:
      - traefik_default
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        delay: 15s
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        max_attempts: 5
        delay: 30s
        window: 600s
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  traefik_logs:
    name: traefik_logs
    external: true
  crowdsec_configs:
    name: crowdsec_configs
    external: true
  crowdsec_data:
    name: crowdsec_data
    external: true

networks:
  traefik_default:
    name: traefik_default
    external: true
```

asquis.yaml
```
poll_without_inotify: false
filenames:
  - /logs/traefik/*.log
labels:
  type: traefik
---
listen_addr: 0.0.0.0:7422
appsec_config: crowdsecurity/appsec-default
name: myAppSecComponent
source: appsec
labels:
  type: appsec
```

profiles.yaml
```
name: initial_ban_remediation
debug: true
filters:
  - Alert.Remediation == true && Alert.GetScope() == "Ip" && GetDecisionsCount(Alert.GetValue()) == 0
decisions:
  - type: ban
    duration: 1h
duration_expr: Sprintf('%dh', (GetDecisionsCount(Alert.GetValue()) + 1) * 1)
notifications:
  - http_default
on_success: break
---
name: progressive_ban_remediation
debug: true
filters:
  - Alert.Remediation == true && Alert.GetScope() == "Ip" && GetDecisionsCount(Alert.GetValue()) > 0
decisions:
  - type: ban
    duration: 1h
duration_expr: Sprintf('%dh', (GetDecisionsCount(Alert.GetValue()) + 1) * 1)
on_success: break
---
name: default_range_remediation
debug: true
filters:
  - Alert.Remediation == true && Alert.GetScope() == "Range"
decisions:
  - type: ban
    duration: 4h
#duration_expr: Sprintf('%dh', (GetDecisionsCount(Alert.GetValue()) + 1) * 4)
# notifications:
#   - slack_default  # Set the webhook in /etc/crowdsec/notifications/slack.yaml before enabling this.
#   - splunk_default # Set the splunk url and token in /etc/crowdsec/notifications/splunk.yaml before enabling this.
#   - http_default   # Set the required http parameters in /etc/crowdsec/notifications/http.yaml before enabling this.
#   - email_default  # Set the required email parameters in /etc/crowdsec/notifications/email.yaml before enabling this.
on_success: break
```

Sample whoami docker swarm stack thats stop working if crowdsec container is down
```
# Stack name: whoami

services:
  whoami:
    image: traefik/whoami:v1.11.0@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
    command:
      - --port=80
      - --name=iamfoo
      - --verbose
    networks:
      - traefik_default
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
        delay: 15s
      rollback_config:
        parallelism: 1
        order: stop-first
      restart_policy:
        condition: any
        max_attempts: 10
        delay: 30s
        window: 600s
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
      labels:
        traefik.enable: 'true'
        traefik.http.routers.whoami.rule: Host(`placeholder`)
        traefik.http.routers.whoami.entrypoints: websecure
        traefik.http.routers.whoami.tls: 'true'
        traefik.http.routers.whoami.tls.certresolver: production
        traefik.http.routers.whoami.service: whoami
        traefik.http.services.whoami.loadbalancer.server.port: '80'
        traefik.http.routers.whoami.middlewares: crowdsec@swarm

networks:
  traefik_default:
    name: traefik_default
    external: true
```

**Version (please complete the following information):**
 - OS: Debian Bookworm
 - Traefik version: 3.3.4
 - Plugin version: v1.4.1
 - Redis ? : none

**To Reproduce**
1. Start traefik stack
2. Start crowdsec stack
3. curl -I anyUrlBehindTraefik.com and get 200 http code
4. Stop crowdsec stack 
5. curl -I anyUrlBehindTraefik.com and get 403 http code
