### ISSUE TITLE
Plugin not working without a backend

### ISSUE THREAD

**Issue by krezovic** [maxlerebourg/crowdsec-bouncer-traefik-plugin#239]
I have configured the middleware on entrypoint and use host-based routing for my services. By default, there's no "catch-all" backend - request to "/" for IP returns 404 and no backend.

I have ordered a scanner that is banned by crowdsec-agent. Here's the corresponding traefik log entry

```
172.104.15.140 - - [11/May/2025:23:51:58 +0000] "GET /cgi-bin/ExportSettings.sh HTTP/2.0" 404 19 "-" "-" 4693 "-" "-" 0ms
192.168.0.5 - - [11/May/2025:23:51:57 +0000] "POST /api/ds/query?ds_type=loki&requestId=loki-data-samples_1 HTTP/3.0" 200 10871 "-" "-" 4689 "monitoring-grafana-REDACTED@kubernetes" "http://10.42.0.153:3000" 224ms
```

Crowdsec agent log:

```
time="2025-05-11T23:51:16Z" level=info msg="Ip 172.104.15.140 performed 'crowdsecurity/http-admin-interface-probing' (6 events over 11.281553003s) at 2025-05-11 23:51:16.169799349 +0000 UTC"
time="2025-05-11T23:52:12Z" level=info msg="Ip 172.104.15.140 performed 'crowdsecurity/http-probing' (11 events over 2.006510158s) at 2025-05-11 23:52:12.335606396 +0000 UTC"
time="2025-05-11T23:52:48Z" level=info msg="Ip 172.104.15.140 performed 'crowdsecurity/http-path-traversal-probing' (12 events over 1m51.068783957s) at 2025-05-11 23:52:48.436874402 +0000 UTC"
time="2025-05-11T23:52:53Z" level=info msg="Ip 172.104.15.140 performed 'crowdsecurity/http-admin-interface-probing' (9 events over 55.670743825s) at 2025-05-11 23:52:53.462773183 +0000 UTC"
time="2025-05-11T23:54:00Z" level=info msg="Ip 172.104.15.140 performed 'crowdsecurity/http-admin-interface-probing' (6 events over 15.045903721s) at 2025-05-11 23:54:00.645236339 +0000 UTC"
```

Traefik config (relevant parts)

```
# Traefik experimental features
experimental:
  # -- Enable traefik experimental plugins
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.4.2 # To update

providers:  # @schema additionalProperties: false
  file:
    # -- Create a file provider
    enabled: true
    # -- Allows Traefik to automatically watch for file changes
    watch: true
    # -- File content (YAML format, go template supported) (see https://doc.traefik.io/traefik/providers/file/)
    content: |
      http:
        middlewares:
          default-https-headers:
            headers:
              stsSeconds: 31536000
              stsIncludeSubdomains: "true"
          crowdsec:
            plugin:
              bouncer:
                enabled: true
                crowdsecMode: stream
                crowdsecAppsecEnabled: true
                crowdsecAppsecHost: crowdsec-appsec-service.crowdsec-system:7422
                crowdsecAppsecFailureBlock: false
                crowdsecAppsecUnreachableBlock: false
                crowdsecLapiScheme: http
                crowdsecLapiHost: crowdsec-service.crowdsec-system:8080
                crowdsecLapiKey: redacted
                # Cloudfare IPv4 https://www.cloudflare.com/ips-v4/#
                forwardedheaderstrustedips:
                  - 173.245.48.0/20
                  - 103.21.244.0/22
                  - 103.22.200.0/22
                  - 103.31.4.0/22
                  - 141.101.64.0/18
                  - 108.162.192.0/18
                  - 190.93.240.0/20
                  - 188.114.96.0/20
                  - 197.234.240.0/22
                  - 198.41.128.0/17
                  - 162.158.0.0/15
                  - 104.16.0.0/13
                  - 104.24.0.0/14
                  - 172.64.0.0/13
                  - 131.0.72.0/22

ports:
  websecure:
    ## -- Enable this entrypoint as a default entrypoint. When a service doesn't explicitly set an entrypoint it will only use this entrypoint.
    # asDefault: true
    port: 8443
    http3:
      ## -- Enable HTTP/3 on the entrypoint
      ## Enabling it will also enable http3 experimental feature
      ## https://doc.traefik.io/traefik/routing/entrypoints/#http3
      ## There are known limitations when trying to listen on same ports for
      ## TCP & UDP (Http3). There is a workaround in this chart using dual Service.
      ## https://github.com/kubernetes/kubernetes/issues/47249#issuecomment-587960741
      enabled: true
      advertisedPort: 443 # @schema type:[integer, null]; minimum:0
    forwardedHeaders:
      # Cloudfare IPv4 https://www.cloudflare.com/ips-v4/#
      # -- Trust forwarded headers information (X-Forwarded-*).
      trustedIPs:
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/13
        - 104.24.0.0/14
        - 172.64.0.0/13
        - 131.0.72.0/22
    #proxyProtocol:
    #  # -- Enable the Proxy Protocol header parsing for the entry point
    #  trustedIPs:
    #    - 10.42.0.0/16
    # --  See [upstream documentation](https://doc.traefik.io/traefik/routing/entrypoints/#tls)
    tls:
      enabled: true
    # -- One can apply Middlewares on an entrypoint
    # https://doc.traefik.io/traefik/middlewares/overview/
    # https://doc.traefik.io/traefik/routing/entrypoints/#middlewares
    # -- /!\ It introduces here a link between your static configuration and your dynamic configuration /!\
    # It follows the provider naming convention: https://doc.traefik.io/traefik/providers/overview/#provider-namespace
    #   - namespace-name1@kubernetescrd
    #   - namespace-name2@kubernetescrd
    middlewares:
      - crowdsec@file
      - default-https-headers@file
```

- Setup allows for Cloudfare IPs in X-Forwarded-For for both plugin and traefik itself
- I have tried without the trustedIPs on both and managed to trigger ban to half of cloudfare network via agent
- I have tried disabling appsec

However, bouncer still does not do anything. If I enable debug logs, I only see it inspect cache for IPs that have a valid router/service (see screenshot). What am I missing?

![Image](https://github.com/user-attachments/assets/617dd4e8-e152-4df7-9ecb-8f7c7671d2b3)
