### ISSUE TITLE
[BUG] v1.4.2 Bouncer returns 403 Forbidden without any active decision

### ISSUE THREAD

**Issue by PinkahPandah** [maxlerebourg/crowdsec-bouncer-traefik-plugin#245]
### **Describe the bug** 🐛

The Traefik bouncer middleware enters a permanent "fail-closed" state where it blocks all requests with a `403 Forbidden` error on any router where it is enabled. This happens even when there are no active decisions or alerts for the client IP in the CrowdSec LAPI.

The block persists even after coordinated restarts of both the Traefik and CrowdSec containers. The only way to get access to the service is to disable the CrowdSec middleware on the router.

### **Expected behavior** 👀

The bouncer should only block a request and return a `403 Forbidden` error if there is an active `ban` decision for the client's IP address issued by the CrowdSec LAPI. If no decision exists, the request should be allowed to pass through to the backend service.

### **Context** 🔎

We have performed extensive debugging and can confirm the following:

1.  **Traefik and CrowdSec are running correctly:** Both containers start without fatal errors in their logs.
2.  **Network connectivity is working:** A test from inside the Traefik container to the CrowdSec LAPI was successful:
    * Command: `docker exec -it traefik /bin/sh -c "apk add curl && curl -v http://crowdsec:8080/v1/heartbeat"`
    * Result: `HTTP/1.1 401 Unauthorized`. This proves that DNS resolution and TCP/HTTP communication between the containers are working perfectly.
3.  **LAPI state is clean:** `docker exec crowdsec cscli decisions list` and `docker exec crowdsec cscli alerts list` both show no entries for the blocked client IP.
4.  **Log Acquisition is working:** `docker exec crowdsec cscli metrics` shows that the Traefik `access.log` is being read and parsed.
5.  **Traefik sees the correct Client IP:** The Traefik `access.log` shows the correct external client IP making the request and receiving a `403` response code. The issue is not related to a misconfiguration of `forwardedHeaders`.

**Plugin Configuration (in `traefik/docker-compose.yml` labels):**
```yaml
labels:
  - "traefik.http.middlewares.crowdsec.plugin.crowdsec.bouncerUrl=http://crowdsec:8080"
  - "traefik.http.middlewares.crowdsec.plugin.crowdsec.crowdsecLapiKey=${CROWDSEC_BOUNCER_API_KEY}" # Key is provided via .env file
```

**Router Configuration (on the target service's labels):**
```yaml
labels:
  - "traefik.http.routers.myservice.middlewares=crowdsec@docker"
```

### **Version (please complete the following information):**
* **OS:** Docker on Linux
* **Traefik version:** 3.0.4
* **Plugin version:** 1.4.2
* **CrowdSec version:** 1.6.8
* **Redis ? :** No

### **To Reproduce**
1.  Set up Traefik and CrowdSec using Docker Compose with the configurations described above.
2.  Enable the CrowdSec middleware on a specific router.
3.  Ensure no decisions exist in CrowdSec for your client IP (`cscli decisions list`).
4.  Attempt to access the URL of the protected router from a web browser.
5.  See the `403 Forbidden` error page.
6.  Disabling the middleware by commenting out the label on the service immediately resolves the issue.

### **Additional Context**
Downgrading the plugin to version v1.4.1 completely resolves the issue. The bug seems to be specific to version v1.4.2.

### **Additional Context**
Context: worked that out while setting up the system with ChatGPT & Gemini

**Comment by ausfestivus** [comment]
Can vouch for this behaviour. Witnessed it this weekend while tooling around with Traefik v3.4 and Crowdsec in my home lab.

I dropped the Traefik plugin back to v1.4.1 and im seeing the behaviour continue though.

@PinkahPandah in your report above, you have:

> Traefik version: 3.0.4

I assume you mean v3.4 as well?

**Comment by PinkahPandah** [comment]
Yeah you are right. I got confused - I'm currently using 3.0.4. Thank you for pointing that out.

**Comment by maxlerebourg** [comment]
Hey,

- Have you read the README?
- Have you really tested the plugin on two versions?

Share a config and/or logs if you really want help....

The famous "configurations described above" that you mention doesn't even exist in your message.
Your issue looks like a response to a prompt; we are human and prefer concise text instead of a soup of words without real content. I speak for myself (but @mathieuHa should share this thought).

We didn't want to respond to this, but @ausfestivus seems to have the same bug. Most of the time, it's a configuration issue, but let's find out.

**Comment by ausfestivus** [comment]
Starting with my traefik config.

Static config (traefik.yaml):

```yaml
experimental:
  plugins:
    crowdsec-bouncer:
      modulename: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.4.2"
```

Dynamic config via file (config.yaml):

```yaml
http:
  middlewares:
    crowdsec:
      plugin:
        crowdsec-bouncer:
          crowdsecLapiKey: "$CROWDSEC_TRAEFIK_BOUNCER_API_KEY"
          crowdsecLapiScheme: http
          crowdsecLapiHost: crowdsec:8080
          enabled: true
```

Now Docker compose config:

```yaml
---
name: traefik-docker-proxy
services:
  traefik:
    depends_on:
      - crowdsec
    container_name: traefik
    image: traefik:v3.4
    restart: always
    networks:
      - backend
      - proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/traefik/config.yaml:/etc/traefik/config.yaml:ro
      - ./data/traefik/certs/:/var/traefik/certs/:rw
      - ./logs/traefik/:/var/log/traefik/:rw

  crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec
    restart: always
    networks:
      - proxy
    expose:
      - "8080"
    environment:
      PGID: "1000"
      COLLECTIONS: "crowdsecurity/traefik crowdsecurity/http-cve"
      BOUNCER_KEY_TRAEFIK: $CROWDSEC_TRAEFIK_BOUNCER_API_KEY
      #LEVEL_DEBUG: "true"
      #LEVEL_INFO: "true"
    volumes:
      - ./logs/crowdsec/:/var/log/crowdsec
      - ./logs/traefik/:/var/log/traefik:ro
      - ./data/crowdsec/:/var/lib/crowdsec/data/
      - ./logs/crowdsec/auth.log:/var/log/crowdsec/auth.log
      - ./config/crowdsec/:/etc/crowdsec
    labels:
      - traefik.enable=false

networks:
  backend:
    external: true
  proxy:
    external: true
```
