### ISSUE TITLE
[BUG] v1.4.2 No log of plugin in traefik logs

### ISSUE THREAD

**Issue by ronan-martin** [maxlerebourg/crowdsec-bouncer-traefik-plugin#247]
**Describe the bug** 🐛
With v1.4.2, I have no logs of the plugin, even with loglevel:DEBUG. No problem with v1.4.1.

**Expected behavior** 👀
Logs should be displayed in traefik logs 

**Context** 🔎
Traefik (docker) and CrowdSec (service in debian) are running correctly, both start without fatal errors in their logs.
All is working perfectly with v1.4.1 but not with the last release.

I only see these lines regarding the plugin :
> DBG github.com/hashicorp/go-retryablehttp@v0.7.7/client.go:661 > Performing request method=GET url=https://plugins.traefik.io/public/download/github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/v1.4.2
> DBG github.com/hashicorp/go-retryablehttp@v0.7.7/client.go:661 > Performing request method=GET url=https://plugins.traefik.io/public/validate/github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/v1.4.2

**Plugin Configuration**
In static conf file traefik.yaml :
```
experimental:
  plugins:
    bouncer:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.4.2"
```
In dynamic file :
```
http:
  middlewares:
    crowdsec:
      plugin:
        bouncer:
          enabled: true
          crowdsecMode: "stream"
          logLevel: DEBUG
          logFilePath: "/var/log/bouncer.log"
          crowdseclapikey: "CROWDSEC_BOUNCER_API_KEY"
          crowdsecLapiHost: "20.23.0.1:8080"
          crowdsecappsecenabled: "true"
          crowdsecAppsecHost: "20.23.0.1:7422"
```

**Version (please complete the following information):**
 - OS: Docker 27.5.1 on Debian 11.11
 - Traefik version: 3.4.1 (but same problem with 2.9.4)
 - Plugin version: 1.4.2
 - Redis ? : no

**To Reproduce**
1. Set up Traefik and CrowdSec plugin using Docker Swarm with the configurations described above.
2. Check Traefik logs and see that there's no logs of the plugin 

**Additional Context**
Downgrading the plugin to version v1.4.1 completely resolves the issue. The bug seems to be specific to version v1.4.2.
