### ISSUE TITLE
Bypassing Crowdsec for local IPs?

### ISSUE THREAD

**Issue by rwjack** [maxlerebourg/crowdsec-bouncer-traefik-plugin#28]
Hello,

I was wondering if this is possible at all with the current implementation?

I know local IPs can be excluded from rate limiting in crowdsec itself, but I would like it if localnet IPs could access services behind traefik, without the bouncer plugin querying crowdsec at all.

I'm guessing some sort of permanent cache would be the solution here (In the case of stream mode), and perhaps even in live mode, the plugin could read IPs from that same "permanent cache".

**Comment by mathieuHa** [comment]
Hello @rwjack ,

Thanks for the Idea.

I think you can already do that directly in Traefik with a duplicated router:

```yaml
http:
  routers:
    to-dev-front-http-service:
      rule: "Host(`example.com`) && !ClientIP(`10.0.0.0/16`, `::1`)"
      service: exposed-service
      entryPoints:
        - websecure
    to-dev-front-https-service:
      rule: "Host(`example.com`) && ClientIP(`10.0.0.0/16`, `::1`)"
      service: exposed-service
      middlewares:
        - "bouncer"
      entryPoints:
        - websecure
```
But I agree It could be a good idea to bypass calls to crowdsec from a trusted IP without duplicating the router.
We'll get back to you in a few days after some reflexion.

Mathieu
