### ISSUE TITLE
Instant 403 Block when Plugin activated

### ISSUE THREAD

**Issue by floari** [maxlerebourg/crowdsec-bouncer-traefik-plugin#62]
**Describe the bug**
As soon as I enable the plugin, i do not have access to my services anymore. They display 403.
When I set Enabled: "False" and restart traefik, I regain access. 

**To Reproduce**
1. Install Traefik Plugin
2. Start Plugin

**Expected behavior**
Access :)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Browser Edge

Thanks!

**Comment by mathieuHa** [comment]
Hi @floari,

First thanks for using our plugin.

Can you provide a bit more detail on the configuration you are using ?

- Are you using docker, docker-compose ?
- What mode is the plugin on ?
- Can Traefik reach the Crowdsec LAPI ?
- What is the version of the plugin
- What is the version of Traefik
- What is the version of Crowdsec

Can you provide the complete configuration for the middleware/plugin like this or using labels:
```yaml
 middlewares:
    crowdsec:
      plugin:
        bouncer:
          enabled: true
          logLevel: DEBUG
          updateIntervalSeconds: 60
          defaultDecisionSeconds: 60
          crowdsecMode: live
          crowdsecLapiHost: crowdsec:8080
          crowdsecLapiScheme: http
```
 Also we've added a logLevel option which you can set to DEBUG.  
This will help us throubleshoot what is happening if you can provid the debug logs on startup and when a request is blocked (403).

My first hint for the instant 403 would be that crowdsec might not be reachable.

Thanks,
Mathieu
