### ISSUE TITLE
Confused about configuring TLS

### ISSUE THREAD

**Issue by rwjack** [maxlerebourg/crowdsec-bouncer-traefik-plugin#65]
Hey, I'm having some issues with the crowdsec container.

When I enable the `tls` option in `config.yml`, and place server certificates generated using `mkcert` into `/etc/crowdsec/certs` of the container, crowdsec keeps crashing and won't start.

I don't need client cert auth, the API key will do fine. But I'm guessing then the crowdsec container still needs to have server side certificates?

middleware config:
```yaml
    crowdsec:
      plugin:
        bouncer:
          enabled: true
          #logLevel: DEBUG
          updateIntervalSeconds: 60
          crowdsecMode: stream
          crowdsecLapiHost: crowdsec-host:1234
          crowdsecLapiKeyFile: /etc/traefik/crowdsecLapiKey
          crowdsecLapiScheme: https
          crowdsecLapiTLSInsecureVerify: true # if the CA below is in the system trust store, do I need this as true or can it be false?
          crowdsecLapiTLSCertificateAuthorityFile: /etc/traefik/certs/selfSignedCA.pem
```

crowdsec config:
```yaml
api:
  client:
    insecure_skip_verify: true
    credentials_path: /etc/crowdsec/local_api_credentials.yaml
  server:
    log_level: info
    listen_uri: 0.0.0.0:8080
    profiles_path: /etc/crowdsec/profiles.yaml
    trusted_ips: # IP ranges, or IPs which can have admin API access
      - 127.0.0.1
      - ::1
    online_client: # Central API credentials (to push signals and receive bad IPs)
      credentials_path: /etc/crowdsec/online_api_credentials.yaml
    tls:
      cert_file: /etc/crowdsec/certs/server.pem #Server side cert
      key_file: /etc/crowdsec/certs/server-key.pem #Server side key
      ca_cert_path: /etc/crowdsec/certs/selfSignedCA.pem #CA used to verify the client certs
```

Also, a strange thing happens when I edit `/etc/crowdsec/local_api_credentials.yaml`.
Even if I add a client generated cert to the file and https:
```
url: https://localhost:8080
ca_cert_path: /tmp/inter.pem #CA to trust the server certificate
key_path: /tmp/agent-key.pem #Client key
cert_path: /tmp/agent.pem #Client cert
```
That file gets overwritten every time the container starts, leading to endless restarts:
```
url: http://0.0.0.0:8080/
login: localhost
password: 1234
```

**Comment by rwjack** [comment]
This is the error I seem to be getting:

```
time="27-12-2022 11:30:37" level=fatal msg="starting outputs error : authenticate watcher (localhost): Post \"http://0.0.0.0:8080/v1/watchers/login\": API error: http code 400, no error message"
```

**Comment by rwjack** [comment]
though not related to the crowdsec container, something is definitely wrong with v1.1.5. I tried creating a new LAPI key and it couldn't even connect:
```
──────────────────────────────────────────────────────────────────────────────────────────────────────────
 Name                    IP Address   Valid   Last API pull          Type             Version   Auth Type
──────────────────────────────────────────────────────────────────────────────────────────────────────────
 traefik-bouncer   local-ip   ✔️       2022-12-27T11:52:24Z   Go-http-client   1.1       api-key
──────────────────────────────────────────────────────────────────────────────────────────────────────────
```

The IP address and Type fields were empty, also the Last API pull seemed to be stuck. When I checked out back to v1.1.4, it had a connection instantaneously, meaning the bouncers list updated to the above output as it should.

**Comment by rwjack** [comment]
Managed to get v1.1.5 working, don't ask me how because I have no idea.

Though the confusion still remains about successfully configuring TLS with an API key.

**Comment by mathieuHa** [comment]
Hi @rwjack,

First let's take a step back and clarify some things about certificates.

When you access a website you usually use HTTP or HTTPS.  
`HTTP` give you access to the content in clear text, anyone looking at the wire or wireless can see what is transmitted.  
`HTTPS` uses certificates generated by a trusted certificate authority with the TLS handshake:

Here is a quick schema that explains steps taken to establish a secure connexion.
![image](https://user-images.githubusercontent.com/16974644/209791759-d4b2009d-93f6-4b7a-9863-df2a24444927.png)

To sum up, the certificates must be placed in the server (here **Crowdsec**) that the client (here **plugin**) will query.   
The plugin must know the CA that signed the server certificate to trust them.   

Here only the **transport layer** has been secured, no **authenticated** has taken placed yet.   

Crowdsec offers 2 choices to authenticate to the LAPI:
* API key sent over HTTP/HTTPS
* Client certificates signed by a trusted CA over HTTPS

When using client certificates, the server (here Crowdsec) will verify that the certificates offered by the client (plugin) are signed by the same trusted CA.

--- 

Please try to see if version **1.1.6** is working better than **1.1.5**, there must be no change between them but I found out yesterday that Traefik download an older version of the plugin code. (Long story the tag to 1.1.5 was previously pointing to old code, and Traefik does not seem to handle this well).

--- 

About the files that get overwritten when you start Crowdsec, I've noticed it as well.
In the docker entrypoint.sh that the container start there are some operations that are performed.  
I guess it will improve over time and be easier to setup. I've had some issues as well.

Feel free to discuss it with @mmetc which works on Crowdsec and has recently improved the docker image.

Hope I could help with some issues you had, please let me know about 1.1.6,  
Thanks,

Mathieu

**Comment by rwjack** [comment]
Hi Mathieu,

Thank you for the elaborate explanation, as always!
I have also come to the same conclusion, but you just confirmed my thoughts.

I will move on with the `API key sent over HTTPS` option, considering my configuration is correct.

The next issue would be Crowdsec overwriting it's files. 
Did you manage to solve this?
Also, @mmetc Any thoughts? 

I'm going to test `v1.4.4-rc2-debian` as we speak.

**Comment by rwjack** [comment]
`v1.4.4-rc2-debian`:

I just changed the following in `local_api_credentials.yaml`
```
- url: http://0.0.0.0:8080
+ url: https://0.0.0.0:8080
login: localhost
password: redacted
```
and uncommented the `tls` part in `config.yaml`.

`local_api_credentials.yaml` still gets overwritten, and on this version the entire `tls` part gets deleted from `config.yaml`

bouncer logs:
```
Dec 28 11:22:10 hostname systemd[1]: Started traefik proxy.
Dec 28 11:22:11 hostname traefik[4082455]: time="2022-12-28T11:22:11+01:00" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
Dec 28 11:22:11 hostname traefik[4082455]: ERROR: CrowdsecBouncerTraefikPlugin: 2022/12/28 11:22:11 crowdsecQuery url:https://crowdsec.host:1234/v1/decisions/stream?startup=true Get "https://crowdsec.host:1234/v1/decisions/stream?startup=true
Dec 28 11:22:11 hostname traefik[4082455]: ERROR: CrowdsecBouncerTraefikPlugin: 2022/12/28 11:22:11 ServeHTTP:isCrowdsecStreamHealthy ip:xxx
Dec 28 11:22:11 hostname traefik[4082455]: ERROR: CrowdsecBouncerTraefikPlugin: 2022/12/28 11:22:11 ServeHTTP:isCrowdsecStreamHealthy ip:xxx
Dec 28 11:22:11 hostname traefik[4082455]: ERROR: CrowdsecBouncerTraefikPlugin: 2022/12/28 11:22:11 ServeHTTP:isCrowdsecStreamHealthy ip:xxx
Dec 28 11:22:11 hostname traefik[4082455]: ERROR: CrowdsecBouncerTraefikPlugin: 2022/12/28 11:22:11 ServeHTTP:isCrowdsecStreamHealthy ip:xxx
```

crowdsec logs:
```
Regenerate local agent 
time="28-12-2022 10:19:31" level=info msg="Machine 'localhost' successfully added to the local 
time="28-12-2022 10:19:31" level=info msg="API credentials dumped to '/etc/crowdsec/local_api_credentials.
Check if lapi needs to automatically register an 
time="28-12-2022 10:19:32" level=info msg="hub index is up to 
time="28-12-2022 10:19:32" level=info msg="Wrote new 533705 bytes index to /etc/crowdsec/hub/.index.
time="28-12-2022 10:19:32" level=info msg="crowdsecurity/linux : up-to-date"
time="28-12-2022 10:19:32" level=info msg="Item 'crowdsecurity/linux' is up-to-date"
time="28-12-2022 10:19:32" level=info msg="Run 'sudo systemctl reload crowdsec' for the new configuration to be effective."
Object parsers/crowdsecurity/whitelists is tainted, skipping
time="28-12-2022 10:19:32" level=warning msg="crowdsecurity/docker-logs : 
time="28-12-2022 10:19:32" level=info msg="Enabled crowdsecurity/docker-logs"
time="28-12-2022 10:19:32" level=info msg="Run 'sudo systemctl reload crowdsec' for the new configuration to be effective."
time="2022-12-28T10:19:33Z" level=warning msg="Deprecation warning: the pid_dir config can be safely removed and is not 
time="28-12-2022 10:19:33" level=info msg="Crowdsec v1.4.4-rc2-linux-
time="28-12-2022 10:19:33" level=info msg="Loading prometheus 
time="28-12-2022 10:19:33" level=info msg="Loading CAPI 
time="28-12-2022 10:19:33" level=info msg="CrowdSec Local API listening on 0.0.0.0:8080"

... SNIP ...

time="28-12-2022 10:19:34" level=info msg="127.0.0.1 - [Wed, 28 Dec 2022 10:19:34 UTC] \"POST /v1/watchers/login HTTP/1.1 200 84.22092ms \"crowdsec/v1.4.4-rc2-linux-80e6a2e60b221c7b306388894d75fdabc8bc51b0\"
time="28-12-2022 10:19:34" level=info msg="capi metrics: metrics sent 
time="28-12-2022 10:19:34" level=info msg="127.0.0.1 - [Wed, 28 Dec 2022 10:19:34 UTC] \"POST /v1/watchers/login HTTP/1.1 200 65.246464ms \"crowdsec/v1.4.4-rc2-linux-80e6a2e60b221c7b306388894d75fdabc8bc51b0\" \""
time="28-12-2022 10:19:34" level=info msg="last CAPI pull is newer than 1h30, skip."
time="28-12-2022 10:19:34" level=info msg="Start pull from CrowdSec Central API (interval: 2h1m8s once, then 2h0m0s)"
time="28-12-2022 10:20:13" level=info msg="traefik.ip - [Wed, 28 Dec 2022 10:20:13 UTC] \"GET /v1/decisions/stream?startup=true HTTP/1.1 200 678.718482ms \"Go-http-client/1.1\" \""
```

**Comment by rwjack** [comment]
One thing I have found out, these errors occur when the bouncer doesn't have the following config line:
`crowdsecLapiTLSInsecureVerify: false`, even though there is no TLS enabled, and the scheme is http.

**Comment by mmetc** [comment]
@rwjack does your container have a LOCAL_API_URL envvar? Is it set to http or https? The option in the credentials file should not be modified if LOCAL_API_URL is empty.

It's a tricky balance to satisfy use cases with configuration files mounted from the host, and configuration from variables (esp. with k8s) but your use case should work.

It might be worth it to use a client certificate especially if you have several agents, but I understand it's a lot easier on k8s where cert-manager does most of the work.

**Comment by rwjack** [comment]
Ahh, that makes sense, I wasn't using the envvar at all.

I've set it to: `https://0.0.0.0:8080`, and I see the changes in the `local_api_credentials.yaml` file,

though now it seems crowdsec won't start at all.
```
time="28-12-2022 11:53:31" level=fatal msg="starting outputs error : authenticate watcher (localhost): Post \"https://0.0.0.0:8080/v1/watchers/login\": could not get jwt token: Post \"https://0.0.0.0:8080/v1/watchers/login\": http: server gave HTTP response to HTTPS client"
```

**Comment by mmetc** [comment]
@rwjack yes, USE_TLS must be set for the lapi or agent to speak https

I'm going to test your use case now -- TLS transport without TLS auth and a single container (i.e. no separate lapi/agent). If we do a 1.4.4-rc3 I might ask you to test it

**Comment by rwjack** [comment]
Gotcha, also forgot to add the tls part in config.yaml, since it got deleted.

**Comment by rwjack** [comment]
Okay, it seems that the crowdsec side is operational now, though still the same here on the bouncer side.

If I restart traefik with the bouncer, `enabled: false`, the logs show this line:
```
Dec 28 13:05:36 redacted traefik[4104529]: ERROR: CrowdsecBouncerTraefikPlugin: 2022/12/28 13:05:36 crowdsecQuery url:https://redacted/v1/decisions/stream?startup=true Get "https://redacted/v1/decisions/stream?startup=tru
e": net/http: invalid header field value for "X-Api-Key"
```

config:
```yaml
    crowdsec:
      plugin:
        bouncer:
          enabled: true
          #logLevel: DEBUG
          updateIntervalSeconds: 60
          crowdsecMode: stream
          crowdsecLapiKeyFile: /etc/traefik/crowdsecLapiKey
          crowdsecLapiHost: redacted:1234
          crowdsecLapiScheme: https
          crowdsecLapiTLSInsecureVerify: false
          crowdsecLapiTLSCertificateAuthorityFile: /etc/traefik/certs/selfSignedCA.pem
```

**Comment by mathieuHa** [comment]
Hi @rwjack,

I'm trying to reproduce with the latest config you gave me.

I added a full exemple for TLS in `exemples/tls-auth` that is close to what you have.   
With one container using HTTPS and API key and one HTTPS and client cert auth.

Thanks @mmetc for helping out!

**Comment by mathieuHa** [comment]
> @rwjack yes, USE_TLS must be set for the lapi or agent to speak https
> 
> I'm going to test your use case now -- TLS transport without TLS auth and a single container (i.e. no separate lapi/agent). If we do a 1.4.4-rc3 I might ask you to test it

I used the following configuration in docker-compose.yaml to enable TLS.  Could not work with bind mount but with env variables.
I never figured out why but I had to disable the agent part of Crowdsec to make it work for the client.

```yaml
  crowdsec:
    image: crowdsecurity/crowdsec:v1.4.3
    container_name: "crowdsec"
    restart: unless-stopped
    environment:
      COLLECTIONS: crowdsecurity/traefik
      CUSTOM_HOSTNAME: crowdsec
      # whoami-foo is authenticating with api key over https
      # whoami-bar is authenticating with tls cert over https
      BOUNCER_KEY_TRAEFIK_FOO: 40796d93c2958f9e58345514e67740e5
      LOCAL_API_URL: https://127.0.0.1:8080
      USE_TLS: "true"
      CERT_FILE: "/etc/crowdsec/certs/server.pem"
      KEY_FILE: "/etc/crowdsec/certs/server-key.pem"
      CACERT_FILE: "/etc/crowdsec/certs/inter.pem"
      AGENTS_ALLOWED_OU: "agent-ou"
      BOUNCERS_ALLOWED_OU: "bouncer-ou"
      LEVEL_DEBUG: "true"
      # Disabled because it restart in loop otherwise
      DISABLE_AGENT: "true"
      # Disabled for the examples
      DISABLE_ONLINE_API: "true"
    volumes:
      - ./config/acquis.yaml:/etc/crowdsec/acquis.yaml
      # - ./config/config.yaml:/etc/crowdsec/config_local.yaml
      # - ./config/local_api_credentials.yaml:/etc/crowdsec/local_api_credentials.yaml:ro
      - crowdsec-certs-tls-auth:/etc/crowdsec/certs/:ro
      - logs-tls-auth:/var/log/traefik:ro
      - crowdsec-db-tls-auth:/var/lib/crowdsec/data/
      - crowdsec-config-tls-auth:/etc/crowdsec/
    labels:
      - "traefik.enable=false"
```
If you have an idea @mmetc i'd appreciate a lot so I can complete this exemple.

The full docker-compose is available at this folder [tls-auth](https://github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/tree/main/exemples/tls-auth).

Thanks,
Mathieu

**Comment by rwjack** [comment]
My docker-compose seems to be much more plain:

I configured the rest of the stuff in `config.yaml`, though I'll give it another go with setting vars in the compose file.
```yaml
version: "3"

volumes:
  db:
  config:

services:

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    restart: unless-stopped

    container_name: crowdsec
    hostname: crowdsec

    environment:
      LOCAL_API_URL: "https://0.0.0.0:8080"
      #COLLECTIONS: "crowdsecurity/traefik"

    ports:
      - "1234:8080"

    volumes:
      - db:/var/lib/crowdsec/data
      - config:/etc/crowdsec
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml
      - /mnt/traefik-logs/:/var/log/traefik/:ro
```

**Comment by mathieuHa** [comment]
Do you still encounter the following error @rwjack ?

> Dec 28 11:22:11 hostname traefik[4082455]: ERROR: CrowdsecBouncerTraefikPlugin: 2022/12/28 11:22:11 crowdsecQuery url:https://crowdsec.host:1234/v1/decisions/stream?startup=true Get "https://crowdsec.host:1234/v1/decisions/stream?startup=true Get "http://crowdsec.host:1234/v1/decisions/stream?startup=true": net/http: invalid header field value for "X-Api-Key"

**Comment by rwjack** [comment]
@mathieuHa Yeah,

bouncer: v1.1.6
traefik: v2.9.6
crowdsec: v1.4.3

**Comment by rwjack** [comment]
```shell
root in x in ~ ❯ cat config.yml |grep LapiKey
          crowdsecLapiKeyFile: /etc/traefik/crowdsecLapiKey
root in x in ~ ❯ cat /etc/traefik/crowdsecLapiKey
redacted
root in x in ~ ❯ ll /etc/traefik/crowdsecLapiKey
.rw------- 33 traefik traefik 28 Dec 13:02 /etc/traefik/crowdsecLapiKey
```

I have also tried using `crowdsecLapiKey`, same error.

**Comment by mathieuHa** [comment]
> ```shell
> crowdsecLapiKeyFile
> ```

Can you confirm that you are using Traefik with a binary and not the container ?  
I think I remember that from an old issue and in Traefik container files are owned by root by default.

If that's the case, I'll test with a binary maybe there are some things weird happening in that case to read the LAPIKEY

**Comment by rwjack** [comment]
Yep, I am using the traefik binary, a VM for itself.

**Comment by rwjack** [comment]
> I'll test with a binary maybe there are some things weird happening in that case to read the LAPIKEY

This seems to be the case

```shell
curl -Lk https://crowdsec-host:1234/v1/decisions/stream?startup=true -H "X-Api-Key: redacted"
```

^ The above works from the traefik VM ^

**Comment by mathieuHa** [comment]
> > I'll test with a binary maybe there are some things weird happening in that case to read the LAPIKEY
> 
> This seems to be the case
> 
> ```shell
> curl -Lk https://crowdsec-host:1234/v1/decisions/stream?startup=true -H "X-Api-Key: redacted"
> ```
> 
> ^ The above works from the traefik VM ^

Hey, I've finally been able to reproduce the X-Api-Key: redacted error.

I've got some work to do to setup a local version of the plugin in that environnement and add more debug log to understand what is happening.  

But I'm getting there..!

**Comment by mathieuHa** [comment]
Alright, I've got it **finally**!

Using `%q` in the DEBUG log I could see that there was some end of line caracters in the LAPIKEY variable fetched from file.

```
DEBUG: CrowdsecBouncerTraefikPlugin: 2022/12/29 21:23:47 key =  "azeuhaohazieojazihazid\n"
```

I will write a fix for this tomorrow and release a new version!

Thanks for taking the time to solve this with me!

Mathieu

**Comment by mathieuHa** [comment]
From RFC [r7230#section-3.2.6](https://www.rfc-editor.org/rfc/rfc7230#section-3.2.6)  Only some chars are allowed in a field header value.  
It might be usefull to check the values entered by user or thoses read (for instance with hidden char) and prevent the plugin to start if bad value is provided.  
![image](https://user-images.githubusercontent.com/16974644/210052479-ad28ba4a-94f2-45b3-8929-c312660d1920.png)

**Comment by rwjack** [comment]
> Alright, I've got it finally!

Ah man I though I was going crazy, literally tried every possible combination.

Glad we got to the bottom of it.

**Comment by mathieuHa** [comment]
I'll create release `1.1.7-beta1` which I'm going to test today, feel free to tell me if that works for you!

**Comment by rwjack** [comment]
Sounds good, let me at it!

**Comment by rwjack** [comment]
Ladies and gentlemen, we have liftoff! :rocket:

**Comment by mathieuHa** [comment]
_Reopening while a stable is not out_

I've managed to get it working with a FILE in a Traefik binary setup.  
However, when I add multiples end of line it only removes the last one, I guess I should remove all of them for the LAPIKEY.

**Comment by rwjack** [comment]
> I guess I should remove all of them for the LAPIKEY.

Good call, never know what the end user is gonna do :shrug:

**Comment by mmetc** [comment]
Good to know, on our side we have decided to rethink a few things, to be released next week. The current image is not rock solid (configuration wise - once it starts, it works :) )

**Comment by mathieuHa** [comment]
> Good to know, on our side we have decided to rethink a few things, to be released next week. The current image is not rock solid (configuration wise - once it starts, it works :) )

Cool, feel free to reach out so we can test it out with you!

**Comment by mathieuHa** [comment]
Release `1.1.7` is now out, I'll close the issue for now, don't hesitate to reopen or create a new one if you find any problem @rwjack 

Best,
Mathieu

**Comment by rwjack** [comment]
@mmetc Commenting here just because all the information is in one place. I just wanted to check the decisions: `cscli decisions list`, and I got this:
```
FATA[04-01-2023 09:28:40 AM] Unable to list decisions : performing request: Get "https://0.0.0.0:8080/v1/alerts?has_active_decision=true&include_capi=false&limit=100": could not get jwt token: Post "https://0.0.0.0:8080/v1/watchers/login": remote error: tls: bad certificate
```

```yaml
version: "3"

volumes:
  db:
  config:

services:

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    restart: unless-stopped

    container_name: crowdsec
    hostname: crowdsec

    environment:
      LOCAL_API_URL: "https://0.0.0.0:8080"
      #COLLECTIONS: "crowdsecurity/traefik"
      USE_TLS: "true"
      CERT_FILE: "/etc/crowdsec/certs/crowdsec.pem"
      KEY_FILE: "/etc/crowdsec/certs/crowdsec-key.pem"
      CACERT_FILE: "/etc/crowdsec/certs/selfsignedCA.pem"
      DISABLE_AGENT: "true"

    ports:
      - "1234:8080"

    volumes:
      - db:/var/lib/crowdsec/data
      - config:/etc/crowdsec
      - ./certs:/etc/crowdsec/certs/:ro
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml
      - /mnt/traefik-logs/:/var/log/traefik/:ro
```

Am I missing something?

**Comment by mmetc** [comment]
@rwjack

You are not missing anything, but the "latest" tag points to 1.4.3 and you need 1.4.4-rc4 which we hope to publish asap. Your validation can help and we are working on better tests.

You can refer to https://github.com/crowdsecurity/crowdsec/blob/releases/1.4.x/docker/README.md

Then, for the "specifies an incompatible key usage" I think the LAPI is picking up the client certificate instead of the server.

we now have both LAPI_CERT_FILE + LAPI_CERT_KEY and CLIENT_CERT_FILE + CLIENT_CERT_KEY

You can use tls encryption (with LAPI_* only)
or you can use tls client auth too (with CLIENT_*)

Let me know, thanks

**Comment by rwjack** [comment]
Gotcha, v1.4.4-rc4 seems to be working as intended, though all the decisions seem to have disappeared.

**Comment by mmetc** [comment]
@rwjack the first command uses the machine endpoint:  `/v1/alerts?has_active_decision=true&include_capi=false&limit=100`

the second uses the endpoint for bouncers, and includes the community blocklist - same as "cscli decisions list -a"

(and if you enable mutual TLS auth you need a bouncer certificate, not an agent certificate)

**Comment by rwjack** [comment]
Ah, understood, though still doesn't explain why the decision list got cleaned? I haven't purged my database or anything.

And I'm only using tls encryption (LAPI_* variables)

**Comment by mathieuHa** [comment]
> Ah, understood, though still doesn't explain why the decision list got cleaned? I haven't purged my database or anything.
> 
> And I'm only using tls encryption (LAPI_* variables)

I'm just guessing here, but can this be because by default local decisions (not community) are only valid for a little time (4h) I believe by default ?

**Comment by rwjack** [comment]
Well first off, I have made that setting different by modifying `profiles.yaml`:
```yaml
decisions:
 - type: ban
   duration: xyh
```

But all in all I remember having a bunch of decisions added every minute, now the list is completely empty, as if that functionality isn't working anymore at all.

@mmetc Let me know if you'd like a separate issue opened in crowdsec, not to spam this issue since we're getting off topic.
