### ISSUE TITLE
[BUG] Using 1.1.9 panic

### ISSUE THREAD

**Issue by Y0ngg4n** [maxlerebourg/crowdsec-bouncer-traefik-plugin#80]
**Describe the bug** 🐛
If i use the 1.1.9 i get this error in the traefik logs:
`time="2023-01-26T22:23:15Z" level=error msg="plugins-storage/sources/gop-2633054613/src/github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin/bouncer.go:169:6: panic" plugin=plugin-crowdsec-bouncer-traefik-plugin module=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin`

**Comment by mathieuHa** [comment]
Hello @Y0ngg4n,

Could you please add a bit more context:
- Environment: (linux, docker, kubernetes)
- Version of Traefik
- Version of Crowdsec
- parameter for the plugin with sensitive data removed

Also please enable debug mode for the plugin and add some more logs we can work on.

We'll take a look tomorrow

Best,
Mathieu

**Comment by Y0ngg4n** [comment]
@mathieuHa how can i enable debug mode for the plugin?

**Comment by mathieuHa** [comment]
You can use the following configuration:
```yaml
 middlewares:
    crowdsec:
      plugin:
        bouncer:
          enabled: true
          logLevel: DEBUG
    ....
```

It will log many information that we believe are usefull to throubleshoot in cases like this.

Also, can you try with version 1.1.8 and see if you observe the same bug ?
1.1.9 was released recently and might have some undetected bugs yet.

Best,

**Comment by Y0ngg4n** [comment]
> You can use the following configuration:
> 
> ```yaml
>  middlewares:
>     crowdsec:
>       plugin:
>         bouncer:
>           enabled: true
>           logLevel: DEBUG
>     ....
> ```
> 
Where exactly to use this?

**Comment by mathieuHa** [comment]
With Kubernetes, you could use like this:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
    name: crowdsec-bouncer
    namespace: treafik
spec:
    plugin:
        crowdsec-bouncer-traefik-plugin:
            crowdsecLapiHost: 10.10.1.1:8080
            CrowdsecLapiKey: APIKEY
            Enabled: "true"
            logLevel: DEBUG
```
