### ISSUE TITLE
[BUG] Stream Mode stops blocking

### ISSUE THREAD

**Issue by cuthulino** [maxlerebourg/crowdsec-bouncer-traefik-plugin#81]
**Describe the bug** 🐛
Unfortunately I do not have exact details but i got this case already multiple times.  
I am not 100% sure what triggers the bug but i think it happened everytime I made a config mistake in traefik, I corrected it and restarted the traefik service. Then the plugin is not blocking anymore.  
  
 I have uptimekuma running and I banned the ip of the container. Like this uptimekuma can check for Code 403 and I see, if it is working.  
I checked it with wget from the container aswell to verify the result and I get a Code 200.   
Switching the middleware from `stream` to `none` works instantly and i get a Code 403.  
Yes I always waited the time to sync the banlist again and much longer. I also reduced polling time to 15 s.
The logs look like the plugin is first serving then checking?!  

The Debug Log of the pluging with `stream` is:
```
Jan 30 09:25:09 traefik traefik[1757]: DEBUG: CrowdsecBouncerTraefikPlugin: 2023/01/30 09:25:09 ServeHTTP ip:10.10.100.38 isTrusted:false
Jan 30 09:25:09 traefik traefik[1757]: DEBUG: CrowdsecBouncerTraefikPlugin: 2023/01/30 09:25:09 cache:GetDecision ip:10.10.100.38
Jan 30 09:25:09 traefik traefik[1757]: DEBUG: CrowdsecBouncerTraefikPlugin: 2023/01/30 09:25:09 ServeHTTP:getDecision ip:10.10.100.38 isBanned:true cache:miss
```
Logs tell me in Stream mode `isBanned:true` but the website is served  
  
This is what it looks like, when i switch to `none` and wget the page:
```
Jan 30 09:39:45 traefik traefik[1757]: DEBUG: CrowdsecBouncerTraefikPlugin: 2023/01/30 09:39:45 ServeHTTP ip:10.10.100.38 isTrusted:false
Jan 30 09:39:45 traefik traefik[1757]: DEBUG: CrowdsecBouncerTraefikPlugin: 2023/01/30 09:39:45 ServeHTTP:handleNoStreamCache ip:10.10.100.38 isBanned:true handleNoStreamCache:banned
```

Output of `cscli decisions list`   on crowdsec is this
``` 
│ 1290066 │ cscli  │ Ip:10.10.100.38   │ kumacheck │ ban    │ | │ 1 │ 999986h15m18.041025541s │ 349     
 ```

**Expected behavior** 👀
When the logs tell me in Stream mode `isBanned:true` the client should be blocked.

**Context** 🔎
 - OS:  Debian11 (LXC)
 - Traefik version: 2.9.6
 - Plugin version: 1.1.9
 - Redis ? : no
  
My Config:
```
experimental:
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.1.9
```
```
    ### crowdsec ###
    crowdsec-bouncer:
      plugin:
        bouncer:
          enabled: true
          logLevel: DEBUG
          crowdsecLapiHost: <host>:<port>
          crowdsecMode: stream
          updateIntervalSeconds: 15
          crowdsecLapiKey: <key>
          clientTrustedIPs:
            - 10.10.1.0/24
            - 10.10.20.0/24
```

**To Reproduce**
Like I wrote I do not have an exact trigger, maybe I will find it in the next days.
