### ISSUE TITLE
How does Live-mode work?

### ISSUE THREAD

**Issue by Allram** [maxlerebourg/crowdsec-bouncer-traefik-plugin#90]
So, this is not a bug-report :)

But i'm strugling a bit on how Live-mode actually work compared to Stream-mode.

When i run my instance in stream-mode (with Redis, thanks for adding the password!), Crowdsec will block IP's when they do something they shouldn't according to the collections i run. This seems to work great.

But when i run my Traefik instance in Live-mode, it never blocks any IP's. But i see that all of the IP's trying to connect to my instance gets a cache:hit, but maybe they are never forwarded to Crowdsec when they are hit in the cache, so that the buckets in Crowdsec will never fill up?

So, when i run Live-mode, will this plugin still send the IP's trying to connect to Crowdsec, or is that only every 60sec? In the latter case, that means it will "never" be triggered by Crowdsec for a ban?

**Comment by mathieuHa** [comment]
Hi @Allram 

I'll explain tomorrow, and I will clarify live mode in the README.
"Spoiler", it's a the same as none mode, but with a one minute cache.
Il will also check that it is still working as intended.

Best,
Mathieu

**Comment by mathieuHa** [comment]
Hey,

To reproduce and understand live mode, you may:

> git clone the main branch of the project then

> I set up the `docker-compose.local.yml` from the repository with the following **edited** to enable debug + live mode:

```
  whoami-foo:
    image: traefik/whoami
    container_name: "simple-service-foo"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.router-foo.rule=Path(`/foo`)"
      - "traefik.http.routers.router-foo.entrypoints=web"
      - "traefik.http.routers.router-foo.middlewares=crowdsec-foo@docker" 
      - "traefik.http.services.service-foo.loadbalancer.server.port=80"
      - "traefik.http.middlewares.crowdsec-foo.plugin.bouncer.enabled=true"
      - "traefik.http.middlewares.crowdsec-foo.plugin.bouncer.LogLevel=DEBUG"
      
      - "traefik.http.middlewares.crowdsec-foo.plugin.bouncer.CrowdsecMode=live"
      
      - "traefik.http.middlewares.crowdsec-foo.plugin.bouncer.crowdseclapikey=40796d93c2958f9e58345514e67740e5"
```

> Then run 

```
docker compose -f docker-compose.local.yml up -d
```

> I finally run docker compose logs -f to see all containers logs

```
docker compose -f docker-compose.local.yml logs -f
```

> Requests are made with: `GET http://localhost/bar`


> First request
```
traefik             | DEBUG: CrowdsecBouncerTraefikPlugin: 2023/03/10 18:00:15 ServeHTTP ip:172.19.0.1 isTrusted:false
traefik             | DEBUG: CrowdsecBouncerTraefikPlugin: 2023/03/10 18:00:15 cache:GetDecision ip:172.19.0.1
traefik             | DEBUG: CrowdsecBouncerTraefikPlugin: 2023/03/10 18:00:15 ServeHTTP:getDecision ip:172.19.0.1 isBanned:false cache:miss
```
> Not in cache so we query crowdsec (see crowdsec logs)
```
crowdsec            | time="10-03-2023 18:00:15" level=info msg="172.19.0.5 - [Fri, 10 Mar 2023 18:00:15 UTC] \"GET /v1/decisions?ip=172.19.0.1&banned=true HTTP/1.1 200 4.792311ms \"Go-http-client/1.1\" \""
``` 
> We add the IP in the cache
```
traefik             | DEBUG: CrowdsecBouncerTraefikPlugin: 2023/03/10 18:00:15 cache:SetDecision ip:172.19.0.1 isBanned:false duration:60s
traefik             | DEBUG: CrowdsecBouncerTraefikPlugin: 2023/03/10 18:00:15 ServeHTTP:handleNoStreamCache ip:172.19.0.1 isBanned:false
```
> Second request, IP is already in the cache
```
traefik             | DEBUG: CrowdsecBouncerTraefikPlugin: 2023/03/10 18:00:24 ServeHTTP ip:172.19.0.1 isTrusted:false
traefik             | DEBUG: CrowdsecBouncerTraefikPlugin: 2023/03/10 18:00:24 cache:GetDecision ip:172.19.0.1
traefik             | DEBUG: CrowdsecBouncerTraefikPlugin: 2023/03/10 18:00:24 ServeHTTP ip:172.19.0.1 cache:hit isBanned:false
```
> Then after a few minutes, same request, ip was not in cache
```
9e3420c324caabd50b7074dd77\" \""
traefik             | DEBUG: CrowdsecBouncerTraefikPlugin: 2023/03/10 18:05:15 ServeHTTP ip:172.19.0.1 isTrusted:false
traefik             | DEBUG: CrowdsecBouncerTraefikPlugin: 2023/03/10 18:05:15 cache:GetDecision ip:172.19.0.1
traefik             | DEBUG: CrowdsecBouncerTraefikPlugin: 2023/03/10 18:05:15 ServeHTTP:getDecision ip:172.19.0.1 isBanned:false cache:miss
crowdsec            | time="10-03-2023 18:05:15" level=info msg="172.19.0.5 - [Fri, 10 Mar 2023 18:05:15 UTC] \"GET /v1/decisions?ip=172.19.0.1&banned=true HTTP/1.1 200 4.504014ms \"Go-http-client/1.1\" \""
traefik             | DEBUG: CrowdsecBouncerTraefikPlugin: 2023/03/10 18:05:15 cache:SetDecision ip:172.19.0.1 isBanned:false duration:60s
traefik             | DEBUG: CrowdsecBouncerTraefikPlugin: 2023/03/10 18:05:15 ServeHTTP:handleNoStreamCache ip:172.19.0.1 isBanned:false
```

Don't hesitate if you have any more question, and if you wanna be alerted when new version arrives, consider starring at/the project ;)
