### ISSUE TITLE
[BUG] When crowdsec is not available at Traefik Start, middleware never become healthy

### ISSUE THREAD

**Issue by mathieuHa** [maxlerebourg/crowdsec-bouncer-traefik-plugin#91]
**Describe the bug** 🐛

![image](https://user-images.githubusercontent.com/16974644/224537851-3ecca5c1-cc38-4cf7-8518-467efcb50532.png)

**Expected behavior** 👀
Traefik fails, then it **retries after one minutes** and eventually **when Crowdsec is ready, it becomes healthy**

**Context** 🔎
Before posting, make sure to use the `logLevel: DEBUG` of the plugin and see if you can fix the error yourself.
If not, post your plugin configuration file (anonimize IP and secret key) and a partial logs file where the error is encountered.

**Version (please complete the following information):**
 - OS: [e.g. Ubuntu, Debian, Docker] docker desktop 4.17
 - Traefik version: [e.g. 2.9.*, 3.0.*] 2.9.6
 - Plugin version: [e.g. 1.1.*] "main"
 - Redis ? : [e.g. 7.0.*] none

**To Reproduce**

change docker-compose.local.yml  
```yml
version: "3.8"

services:
  traefik:
    image: "traefik:v2.9.6"
    container_name: "traefik"
    restart: unless-stopped
    command:
      - "--log.level=DEBUG"
      - "--accesslog"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"

      - "--experimental.localplugins.bouncer.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - logs-local:/var/log/traefik
      - ./:/plugins-local/src/github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
    ports:
      - 80:80
      - 8080:8080
    depends_on:
      - crowdsec

  whoami-foo:
    image: traefik/whoami
    container_name: "simple-service-foo"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.router-foo.rule=Path(`/foo`)"
      - "traefik.http.routers.router-foo.entrypoints=web"
      - "traefik.http.routers.router-foo.middlewares=crowdsec-foo@docker" 
      - "traefik.http.services.service-foo.loadbalancer.server.port=80"
      - "traefik.http.middlewares.crowdsec-foo.plugin.bouncer.enabled=true"
      - "traefik.http.middlewares.crowdsec-foo.plugin.bouncer.crowdsecMode=stream"
      - "traefik.http.middlewares.crowdsec-foo.plugin.bouncer.crowdsecLapiHost=crowdsec:8080"
      - "traefik.http.middlewares.crowdsec-foo.plugin.bouncer.loglevel=DEBUG"
      - "traefik.http.middlewares.crowdsec-foo.plugin.bouncer.crowdseclapikey=40796d93c2958f9e58345514e67740e5"

  crowdsec:
    image: crowdsecurity/crowdsec:v1.4.6
    container_name: "crowdsec"
    restart: unless-stopped
    environment:
      COLLECTIONS: crowdsecurity/traefik
      CUSTOM_HOSTNAME: crowdsec
      BOUNCER_KEY_TRAEFIK_1: 40796d93c2958f9e58345514e67740e5
      BOUNCER_KEY_TRAEFIK_2: 44c36dac5c4140af9f06f397508e82c7
    volumes:
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      - logs-local:/var/log/traefik:ro
      - crowdsec-db-local:/var/lib/crowdsec/data/
      - crowdsec-config-local:/etc/crowdsec/
    labels:
      - "traefik.enable=false"
volumes:
  logs-local:
  crowdsec-db-local:
  crowdsec-config-local:
```
docker-compose -f docker-compose.local.yml up -d

Go to http://localhost:8080/dashboard/#/http/routers/router-foo@docker

![image](https://user-images.githubusercontent.com/16974644/224537986-e34d00cd-ddc5-48f4-b6ec-1eba09f60ed6.png)

---
If you like the plugin, please consider starring it, so you can get updates and we get some more visibility ✨
