### ISSUE TITLE
[BUG] Missing plugin version tag in sample configuration causes Traefik to crash with unclear error message

### ISSUE THREAD

**Issue by TrevisGordan** [maxlerebourg/crowdsec-bouncer-traefik-plugin#96]
**Describe the bug** 🐛
In the sample configuration for the crowdsec-bouncer-traefik-plugin for Traefik, the plugin version tag is missing. When the version tag is not included, traffic crashes and displays a non-descriptive error message: "invalid middleware \"crowdsec@file\" configuration: invalid middleware type or middleware does not exist."

**Expected behavior** 👀
The sample configuration should include the plugin version tag, preventing traffic crashes and unclear error messages.

**Context** 🔎
I encountered this error while trying to set up the crowdsec-bouncer-traefik-plugin for Traefik using the provided sample configuration.

**Version (please complete the following information):**
- OS: Docker
- Traefik version: 2.9.*
- Plugin version: version: v1.1.7 tag solved the issue have not tried higher tags.

**To Reproduce**
1. Set up the crowdsec-bouncer-traefik-plugin using the provided sample configuration without the plugin version tag.
2. Start Traefik.
3. Observe the error message: "invalid middleware \"crowdsec@file\" configuration: invalid middleware type or middleware does not exist."

**Solution**
Add the missing plugin version tag to the sample configuration, so that users can avoid this error.

```yaml
# Static configuration

experimental:
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: vX.Y.Z # Replace with the appropriate version
```
**Additional context**
Please update the sample configuration in the documentation to include the plugin version tag, or investigate why it is not working without the version tag. - i want to save others from this pain ;) - despite this it is one of the best documented plugins in the lab!
